### ISSUE TITLE
Add documentation on how to contribute

### ISSUE THREAD

**Issue by cesarsouza** [migueldeicaza/TensorFlowSharp#1]
Hello there,

I know its super early to add such request as the repository has been created ~10h ago. However, I am deeply interested in contributing to this project. I have authored a [general machine learning framework for .NET](https://github.com/accord-net/framework) and I am also a researcher on computer vision currently working with Keras, TensorFlow and Theano. So I might know a thing or two on both the .NET and TensorFlow camps, and I am offering to help on whatever is needed (in my free time, though).

Cesar

**Comment by migueldeicaza** [comment]
Good point Cesar.

I will try to put something together, right now I am doing a line-by-line port of the C API test suite:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api_test.cc

Into the sample program, to exercise the API.  As I do that, I am both finding opportunities to improve the API (like the recent indexers - I like then very much) as well as mistakes I made on the API.

I will start filing Issues to track tasks and ideas.

**Comment by migueldeicaza** [comment]
I have both updated the README with guidance, as well as filed a number of issues as I did the binding.

The binding is almost done, with only some fringe features missing, and I am now switching my attention to improving the API usability from C# and F#.
