### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by oregoncicada** [migueldeicaza/TensorFlowSharp#103]
Simple use case failed with a vanilla install and configuration.

1. Fresh install of Python on Windows x64
2. Fresh install of tensorflow using pip (no GPU support)
3. Fresh install of Visual Studio 2017 Enterprise
4. Create new command-line project
5. In project properties, target .NET Framework 4.6.1
6. Under VS Tools menu, select nuget console and run "Install-Package TensorFlowSharp"
7. In project, add reference to packages\TensorFlowSharp.1.2.2\lib\net461\TensorFlowSharp.dll
8. In Program.cs, "using TensorFlow;" and in Main "var session = new TFSession()"

Hit run. Program immediately crashed with exception...

`System.BadImageFormatException: 'Could not load file or assembly 'TensorFlowSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.'
`

**Comment by thepok** [comment]
just go to project/properties/build and use 64bits

**Comment by oregoncicada** [comment]
Thanks, that did it.

**Comment by westside** [comment]
![image](https://user-images.githubusercontent.com/1837913/39035340-957d5550-44b4-11e8-81e4-cc115fff7396.png)

Thanks @thepok  I've changed platform target and works nicely.

**Comment by Ahmetcanb** [comment]
thank you so much @thepok  that worked for me
