### ISSUE TITLE
graph.Import throws "Invalid GraphDef" error

### ISSUE THREAD

**Issue by khanyuriy** [migueldeicaza/TensorFlowSharp#110]
Hi!
I have read posts about models that size is greater than 70MB. But my model have less. Actually 62,2 КБ
How can check that TensorFlowSharp bindings are compatible with saved_model.pb that i have ?

TensorFlowSharp 1.0.0.0

**Comment by migueldeicaza** [comment]
This is a TensorFlow issue, please report it there.
