### ISSUE TITLE
Loading model checkpoint fails

### ISSUE THREAD

**Issue by r3db** [migueldeicaza/TensorFlowSharp#112]
Hi Miguel.
This is what I'm doing:

```csharp
using (var graph = new TFGraph())
{
    graph.Import(File.ReadAllBytes(@"model.tf.meta"));
}
```

And these are the files I'm trying to load, (they are checkpoints)

![image](https://user-images.githubusercontent.com/9978724/29129216-fc7d4ff8-7d1d-11e7-9d56-e830799ba901.png)

I always get this exception: `TensorFlow.TFException: Invalid GraphDef`
I was wondering if there is a way to load checkpoints.

Or if not... How do I convert these checkpoints into *.pb files, (which is what the inception demo is loading).

Cheers.

**Comment by Aminullah6264** [comment]
Dear @r3db 
Firstly you need to freez you checkpoint files 
these four file can not be loaded in C# you need ("YOUR_MODEL.pb") .pb for loading this.

**Comment by Aminullah6264** [comment]
var model = File.ReadAllBytes("D:\\Projects\\MyModel\\frozen_model.pb") 
graph.Import(model);

**Comment by r3db** [comment]
@Aminullah6264 Thanks for you help.
I was trying to avoid that.

The reason I was trying to load a checkpoint is because I cannot freeze my model I keep getting `KeyError: "The name 'Adam' refers to an Operation not in the graph."`
I followed this tutorial: https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc

**Comment by Aminullah6264** [comment]
i follow the same but was done.
What you are confused about?

**Comment by r3db** [comment]
Well maybe I did something really stupid... and I cannot figure out what is it.
This is my network architecture (notice the adam optimizer at the bottom):

```python
def create_network(width, height, size):
    network = input_data(shape=[None, width, height, 1], name="input")

    network = conv_2d(network, 32, 7, activation="relu", regularizer="L2")
    network = max_pool_2d(network, 2)

    (...)

    network = fully_connected(network, 128, activation="relu")
    network = dropout(network, "0.5")

    network = fully_connected(network, size, activation="relu")
    network = regression(network, optimizer='adam', learning_rate=0.0001, loss="mean_square", metric=None, name="output")

    return network;
```

I use it like this:

```
network = create_network(width, height, size)
model = tflearn.DNN(network, tensorboard_verbose=0)
```

It trains fine
And I save it like this:

`model.save("model.tf")`

![image](https://user-images.githubusercontent.com/9978724/29129216-fc7d4ff8-7d1d-11e7-9d56-e830799ba901.png)

I can load it back and continue training... no problem.... until I do this:

`freeze_graph("/some-checkpoint-location")` 
I'm using the exact code from the tutorial and this is the result

```
Traceback (most recent call last):
  File "detection.py", line 164, in <module>
    mcu.freeze_graph("models/60x60-15x15-1-5x5-false-true-02/1_0.000000")
  File "../utils\converter_utility.py", line 26, in freeze_graph
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 1595, in import_meta_graph
    **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 499, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\importer.py", line 308, in import_graph_def
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 2339, in create_op
    self._add_op(ret)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 2033, in _add_op
    "is already used" % op.name)
ValueError: cannot add op with name Adam/Total_Loss/moving_avg as that name is already used
```

**Comment by Aminullah6264** [comment]
firstly add this line after
model.save("model.tf")
tf.train.write_graph(sess.graph_def, 'Directory where you want to save .pb file', 'trainModel.pb',as_text=True)

secondly you need to freez this .pb file and with those checkpoint file using this code
this code work for me if any error coming plz upload in detail

import os, argparse
from tensorflow.python import pywrap_tensorflow
import tensorflow as tf
from tensorflow.python.framework import graph_util
from tensorflow.python.tools.inspect_checkpoint import print_tensors_in_checkpoint_file
dir = os.path.dirname(os.path.realpath(__file__))

def freeze_graph(model_folder):
    checkpoint = tf.train.get_checkpoint_state(model_folder)
    input_checkpoint = checkpoint.model_checkpoint_path
    
    # We precise the file fullname of our freezed graph
    absolute_model_folder = "/".join(input_checkpoint.split('/')[:-1])
    output_graph = absolute_model_folder + "/trainModel.pb"
    output_node_names=[]
    reader = pywrap_tensorflow.NewCheckpointReader(input_checkpoint)
    var_to_shape_map = reader.get_variable_to_shape_map()
    for key in var_to_shape_map:
        output_node_names.append(key)
            print("tensor_name: ", key)
    output_node_names=str(output_node_names)       
        output_node_names = str([n.name for n in tf.get_default_graph().as_graph_def().node])
        output_node_names=output_node_names.replace('u\'','\'')
        output_node_names=output_node_names.replace('[','')
        output_node_names=output_node_names.replace(']','')
        output_node_names=output_node_names.replace('\'','')
       
    
    

    clear_devices = True
    
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)
    


    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()
  
    with tf.Session() as sess:
        
        saver.restore(sess, input_checkpoint)
        

        output_graph_def = graph_util.convert_variables_to_constants(
            sess, # The session is used to retrieve the weights
            input_graph_def, # The graph_def is used to retrieve the nodes 
            output_node_names.split(',')# The output node names are used to select the usefull nodes
        ) 

        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))


freeze_graph("PATH TO YOUR PB and checkpoint files")

**Comment by r3db** [comment]
Unfortunately I get the same error:
Here's the full output:

```
----> Tensor Name: FullyConnected/W/Adam
----> Tensor Name: Training_step
----> Tensor Name: Conv2D_3/b/Adam
----> Tensor Name: FullyConnected_1/b/Adam_1
----> Tensor Name: FullyConnected_1/b/Adam
----> Tensor Name: FullyConnected/b
----> Tensor Name: Adam/beta1_power
----> Tensor Name: Conv2D_3/W/Adam
----> Tensor Name: Conv2D_4/b/Adam_1
----> Tensor Name: val_acc
----> Tensor Name: Conv2D_2/b
----> Tensor Name: Conv2D_1/W/Regularizer/L2-Loss/moving_avg
----> Tensor Name: Conv2D_2/b/Adam_1
----> Tensor Name: FullyConnected_1/W
----> Tensor Name: Conv2D_4/W
----> Tensor Name: Conv2D_3/b
----> Tensor Name: Conv2D/W/Adam_1
----> Tensor Name: Conv2D/b/Adam_1
----> Tensor Name: FullyConnected_1/PReLU/alphas/Adam_1
----> Tensor Name: Conv2D_1/W
----> Tensor Name: Conv2D_3/W/Adam_1
----> Tensor Name: Conv2D_4/b
----> Tensor Name: Global_Step
----> Tensor Name: Conv2D_3/W
----> Tensor Name: Conv2D_4/W/Adam
----> Tensor Name: Conv2D_3/W/Regularizer/L2-Loss/moving_avg
----> Tensor Name: Conv2D_1/b
----> Tensor Name: FullyConnected/b/Adam
----> Tensor Name: FullyConnected_1/W/Adam_1
----> Tensor Name: FullyConnected_1/W/Adam
----> Tensor Name: val_loss
----> Tensor Name: Conv2D/W/Adam
----> Tensor Name: is_training
----> Tensor Name: Conv2D_4/b/Adam
----> Tensor Name: Conv2D_2/b/Adam
----> Tensor Name: Conv2D_3/b/Adam_1
----> Tensor Name: FullyConnected_1/PReLU/alphas/Adam
----> Tensor Name: Conv2D_1/W/Adam
----> Tensor Name: FullyConnected_1/b
----> Tensor Name: FullyConnected/PReLU/alphas
----> Tensor Name: Conv2D/b
----> Tensor Name: Conv2D_2/W/Regularizer/L2-Loss/moving_avg
----> Tensor Name: Conv2D_1/W/Adam_1
----> Tensor Name: Conv2D_1/b/Adam_1
----> Tensor Name: Conv2D_2/W/Adam_1
----> Tensor Name: Conv2D_1/b/Adam
----> Tensor Name: Adam/beta2_power
----> Tensor Name: Custom-L2-Loss/L2Loss/moving_avg
----> Tensor Name: Conv2D/W/Regularizer/L2-Loss/moving_avg
----> Tensor Name: FullyConnected/W/Adam_1
----> Tensor Name: FullyConnected/b/Adam_1
----> Tensor Name: Conv2D_4/W/Adam_1
----> Tensor Name: FullyConnected_1/PReLU/alphas
----> Tensor Name: Conv2D/W
----> Tensor Name: Conv2D_2/W/Adam
----> Tensor Name: Conv2D_2/W
----> Tensor Name: Conv2D/b/Adam
----> Tensor Name: FullyConnected/PReLU/alphas/Adam
----> Tensor Name: Conv2D_4/W/Regularizer/L2-Loss/moving_avg
----> Tensor Name: FullyConnected/W
----> Tensor Name: Adam/Total_Loss/moving_avg
----> Tensor Name: FullyConnected/PReLU/alphas/Adam_1

Traceback (most recent call last):
  File "detection.py", line 220, in <module>
    freeze_graph("models/{0}/140_0.101980/".format(directory_format))
  File "detection.py", line 202, in freeze_graph
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)
  File "C:\Users\r3db\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 1686, in import_meta_graph
    **kwargs)
  File "C:\Users\r3db\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 504, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "C:\Users\r3db\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\framework\importer.py", line 311, in import_graph_def
    op_def=op_def)
  File "C:\Users\r3db\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 2509, in create_op
    self._add_op(ret)
  File "C:\Users\r3db\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 2203, in _add_op
    "is already used" % op.name)
ValueError: cannot add op with name Adam/Total_Loss/moving_avg as that name is already used
```

**Comment by Aminullah6264** [comment]
Dear I think you not have understand what I said
Firstly, during training phase you should save you model and pb file using this lines

model.save("model.tf")
tf.train.write_graph(sess.graph_def, 'Directory where you want to save .pb file', 'trainModel.pb',as_text=True)


when you have finish training and save the file then use that code what I told you.
then save those tensor name in output_node_names  string variable having no space and each one sprite using , comma 

In your case I think include only these two lines
output_node_names=output_node_names.replace('\'','')
output_node_names=output_node_names.replace(' ','')

removing space and ' single cc.


because this is the main line where you need the output names

output_graph_def = graph_util.convert_variables_to_constants(
        sess, # The session is used to retrieve the weights
        input_graph_def, # The graph_def is used to retrieve the nodes 
        output_node_names.split(',')# The output node names are used to select the usefull nodes
    ) 

try if you still have problem 
I will give time on TeamViewer for this

**Comment by r3db** [comment]
I did exactly that. :)

I saved the checkpoints by doing: `model.save("model.tf")`
I the generated `trainModel.pb` using this: `tf.train.write_graph(sess.graph_def, 'Directory where you want to save .pb file', 'trainModel.pb',as_text=True)`

The `trainModel.pb` is in the **same folder** as the checkpoints.
Finally I ran `freeze_graph("PATH TO YOUR PB and checkpoint files")` in that exact same folder.

And by doing so I get: `ValueError: cannot add op with name Adam/Total_Loss/moving_avg as that name is already used`.

As I said in the email I'm willing to compensate for any help on this problem.

**Comment by r3db** [comment]
@Aminullah6264 thanks for all the help.
Unfortunately this is not a TensorflowSharp topic so I'll close it down.

**Comment by Aminullah6264** [comment]
I think you need to same your meta file from session not outside session.

Regards
Amin Ullah
Intelligent Media Lab, Department of Software, College of Software
Convergence, Sejong University, Seoul, Republic of Korea
Skype: aminullah62641
Facebook: www.facebook.com/aminullah6264
