### ISSUE TITLE
Deploy new version on nuget

### ISSUE THREAD

**Issue by doxakis** [migueldeicaza/TensorFlowSharp#113]
Hi,

Can you deploy a new version on nuget to fix some issues?
Last version was deployed on 2017-06-28.

Thanks!

**Comment by migueldeicaza** [comment]
I will, it is just a bit difficult, as I am about to go on a short vacation, and do not want to release it without testing across the board.

**Comment by migueldeicaza** [comment]
To not keep you waiting, I have uploaded a test version, it has the label "pre1" to allow for you to test it, and if it works out, I can rename it and make it final when I get back:

https://www.nuget.org/packages/TensorFlowSharp/1.3.0-pre1
