### ISSUE TITLE
Converting to and from TFDataType and System.Type

### ISSUE THREAD

**Issue by cesarsouza** [migueldeicaza/TensorFlowSharp#116]
Please, may I ask if there are there any standard ways of converting betwen TFDataType and System.Type currently exposed in the API?

If not, can I send a PR marking [TypeFromTensorType](https://github.com/migueldeicaza/TensorFlowSharp/blob/master/TensorFlowSharp/Tensor.cs#L754) as public and adding a new TensorTypeToType method there?

Regards,
Cesar

**Comment by migueldeicaza** [comment]
Let us make it public, and add the equivalent method on the way back.

**Comment by cesarsouza** [comment]
Great! I will send a pull request soon.

**Comment by migueldeicaza** [comment]
Merged the patch
