### ISSUE TITLE
How to use PartialRun() in TensorFlowSharp?What is the meaning and usage of TFOperation[] in it?

### ISSUE THREAD

**Issue by FesianXu** [migueldeicaza/TensorFlowSharp#119]
Now i try to use the PartialRun() which is claimed that can be run partially in a session.Before use this method, i need to call PartialRunSetup() to prepare a RunningToken. 
API like following:
```
PartialRunToken PartialRunSetup(TFOutput[], TFOutput[], TFOperation[], TFStatus)
TFTensor[] PartialRun (PartialRunToken token, TFOutput[] inputs, TFTensor[] inputValues, TFOutput[] outputs, TFOperation[] targetOpers);
```
I can understand the most paramters , what puzzle me is that What is the meaning and usage of TFOperation[] in both of the methods?

**Comment by cesarsouza** [comment]
Hi @FesianXu, please post an example of what has worked for you for others who might also run into the same problem 👍 

Regards,
Cesar

**Comment by FesianXu** [comment]
Hi, Cesar @cesarsouza,  i'm sorry to tell you that i still have not figure it out, but i found that the normal `Run()`  can also solve my problem(I had a misunderstanding about run() before) so i closed the issue, maybe i should reopen it again so those who faces the same problem can discuss together.

**Comment by Dorokhov** [comment]
Hi @FesianXu , the TFOperation[] parameters are just instances of operations you want to run partially and you can get those from TFOutput object. Please, have a look at my pull request containing C# example of PartialRun() usage. Hope, it will help.
https://github.com/migueldeicaza/TensorFlowSharp/pull/121

**Comment by migueldeicaza** [comment]
Thanks!   Patch merged.
