### ISSUE TITLE
How to specify the TFOutput type?

### ISSUE THREAD

**Issue by r3db** [migueldeicaza/TensorFlowSharp#130]
I'm not sure if this is the correct location to pose this question.
But I haven't found answers anywhere.

This code:

```csharp
using (var graph = new TFGraph())
{
    graph.Import(File.ReadAllBytes("graph.pb"));  // Frozen Graph
    var session = new TFSession(graph);
    var input = new TFTensor(new float[60 * 60]); // Let's pretend this is 60 by 60 image.

    var w = session.Run(new[] {graph["input_node/X"][0]}, new[] { input }, new[] { graph["output_node/Y"][0] });
}
```

throws this exception:

```csharp
Unhandled Exception: TensorFlow.TFException: You must feed a value for placeholder tensor 'output_node/Y' with dtype float
         [[Node: output_node/Y = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
   at TensorFlow.TFStatus.CheckMaybeRaise(TFStatus incomingStatus, Boolean last)
   at TensorFlow.TFSession.Run(TFOutput[] inputs, TFTensor[] inputValues, TFOutput[] outputs, TFOperation[] targetOpers, TFBuffer runMetadata, TFBuffer runOptions, TFStatus status)
```

It's telling me my output needs to be of type `float` which internally, (I believe), maps to: `DT_FLOAT`.
How do I do that?

If I look at my pbtext file:

![image](https://user-images.githubusercontent.com/9978724/29797476-2832dc36-8c4f-11e7-8c7b-6ea6f06172e9.png)

The type is already `DT_FLOAT`. What am I missing.
Kind Regards

**Comment by migueldeicaza** [comment]
You are using the most low-level API and you would need to specify the output (which is missing).

You are better off using the runner API, call `GetRunner` on your session, and this will return an object that surfaces a few methods that simplify this process, you describe your inputs there, the targets and outputs and then call Run ().

See the uses in `SampleTest` for some examples.

**Comment by r3db** [comment]
Hi Miguel thanks for the feedback.
I checked the `SampleTest` here: https://github.com/migueldeicaza/TensorFlowSharp/blob/master/Examples/ExampleInceptionInference/Program.cs#L88-L101 and changed my sample accordingly:

```csharp
using (var graph = new TFGraph())
{
    graph.Import(File.ReadAllBytes("graph.pb"));  // Frozen Graph
    var session = new TFSession(graph);
    var input = new TFTensor(new float[60 * 60]); // Let's pretend this is 60 by 60 image.

    var runner = session.GetRunner();
    runner.AddInput(graph["input_node/X"][0], input).Fetch(graph["output_node/Y"][0]);
    runner.Run()
}
```

And I keep getting the same exception:
```
Unhandled Exception: TensorFlow.TFException: You must feed a value for placeholder tensor 'output_node/Y' with dtype float and shape [?,48]
         [[Node: output_node/Y = Placeholder[dtype=DT_FLOAT, shape=[?,48], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
   at TensorFlow.TFStatus.CheckMaybeRaise(TFStatus incomingStatus, Boolean last)
   at TensorFlow.TFSession.Run(TFOutput[] inputs, TFTensor[] inputValues, TFOutput[] outputs, TFOperation[] targetOpers, TFBuffer runMetadata, TFBuffer runOptions, TFStatus status)
   at TensorFlow.TFSession.Runner.Run(TFStatus status)
```

You said in the previous example I was missing the output:
I don't see where, could you please point me out.

**Comment by oferbentovim** [comment]
did you get an answer? could you solve it?
