### ISSUE TITLE
Why the "TF" prefix?

### ISSUE THREAD

**Issue by cglong** [migueldeicaza/TensorFlowSharp#134]
Title should explain my question 🙂 Prefixing the classes with `TF` reminds me of patterns more common in languages that lack namespace support, like ObjC. Might just be me, but I think `new Session(graph)` reads more idiomatically than `new TFSession(graph)`.

**Comment by migueldeicaza** [comment]
While namespaces do exist, my working theory at the beginning was that TensorFlowSharp would likely live side-by-side other frameworks (Accord, KerasSharp, Infer.NET and so on) and figured that we would end up conflicting with names and while the pure uses would look simpler, the combined cases would look contrived.

It could have gone either way really, but there were reasons for both, and I just picked one.
