### ISSUE TITLE
Managed Debugging Assistant 'CallbackOnCollectedDelegate'

### ISSUE THREAD

**Issue by brunovollmer** [migueldeicaza/TensorFlowSharp#141]
When I run this lines of code: 

```
graph = new TFGraph();
model = File.ReadAllBytes(ModelsFile);
graph.Import(model, "");
```
I recieve a  'CallbackOnCollectedDelegate' exception for the type "TensorFlowSharp!TensorFlow.TFBuffer+BufferReleaseFunc::Invoke" . Does anybody knows how to prevent it. Both graph and model a static variables in the class.

**Comment by migueldeicaza** [comment]
Can you provide a complete test case?    I do not see a scenario where this would happen

**Comment by doxakis** [comment]
#135

**Comment by migueldeicaza** [comment]
Ah, can you try the 1.3.0-pre version and report back?

Will close until then (and will try to publish 1.3.0 as official as well tonight)
