### ISSUE TITLE
Native lib from tensorflow nightly build and TensorFlowSharp nuget package provide different APIs

### ISSUE THREAD

**Issue by Dorokhov** [migueldeicaza/TensorFlowSharp#146]
I just noticed that 'libtensorflow.dylib' from the TesorFlowSharp nuget package and from tensorflow nightly build artifacts (for instance, [from here](http://ci.tensorflow.org/view/Nightly/job/nightly-libtensorflow/TYPE=mac-slave/82/artifact/lib_package/libtensorflow-cpu-darwin-x86_64.tar.gz ) or [from here](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-darwin-x86_64-1.3.0.tar.gz) ) provide different APIs.

The problem is that we use the 'libtensorflow.dylib' from nightly build in CI on Travis and it's missing bitwise operations like BitwiseAnd, BitwiseOr and others, but they all exist in the library shipping in TensorFlowSharp nuget.

Where do we get the native libraries for the nuget package and how can we download and use them on the Travis CI?

**Comment by migueldeicaza** [comment]
Mhm, this is a problem.

I used a link to the latest binaries, and this will be changing continously.   Perhaps time to find a stable url for these.

I am afraid that the only way of getting a reliable check right now is to extract the files from the existing NuGet.
