### ISSUE TITLE
Install instruction are not clear

### ISSUE THREAD

**Issue by RubyGemer** [migueldeicaza/TensorFlowSharp#149]
First, 

`nuget install TensorFlowSharp` is copying files in home directly. Where should copy these files? Shouldn't these files show go with other .net packages/libraries? 

<img width="352" alt="screen shot 2017-09-20 at 8 20 51 pm" src="https://user-images.githubusercontent.com/15967311/30656124-9d9212ea-9e50-11e7-9d11-a283ccc200f9.png">

Second, I copied the files to `usr/local`
libtensorflow-cpu-darwin-x86_64-1.1.0.tar.gz

<img width="828" alt="screen shot 2017-09-20 at 8 21 42 pm" src="https://user-images.githubusercontent.com/15967311/30656133-a632c19c-9e50-11e7-8dbc-18dec633f9f4.png">

Now what? I'm not a ML guy. I am learning ML & I am beginning it in C#

**Comment by migueldeicaza** [comment]
Just open one of the example csproj or solution files and run in 64bit mode.

**Comment by RubyGemer** [comment]
`nuget install TensorFlowSharp`  has copied everything in home directory. All the libraries. They should somewhere specific...where other .net libraries are

So, Visual Studio Community OSX doesn't recognize TensorFlow

<img width="1181" alt="screen shot 2017-09-22 at 11 23 06 am" src="https://user-images.githubusercontent.com/15967311/30731169-5cd8f87e-9f89-11e7-8745-a1e778de72a1.png">

**Comment by RubyGemer** [comment]
also even though I've installed TensorFlowSharp from within the inside of Visual Studio. All errors go....where will see the output? 

I'm building the project and nothing happens 
<img width="1090" alt="screen shot 2017-09-22 at 11 50 03 am" src="https://user-images.githubusercontent.com/15967311/30731665-63f674e4-9f8c-11e7-9524-31fd25acdd59.png">

**Comment by RubyGemer** [comment]
@migueldeicaza sir just get me into head start. I'll pick from there. I want to do serious contribution to this project 👍
