### ISSUE TITLE
OPGenerator project shows error on built protobuf-net

### ISSUE THREAD

**Issue by RubyGemer** [migueldeicaza/TensorFlowSharp#152]
I have installed protobuf-net using nuget in Visual Studio

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'OpGenerator:required_attrs' (1) due to: Could not load file or assembly 'protobuf-net, Version=2.3.2.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. assembly:protobuf-net, Version=2.3.2.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67 type:<unknown type> member:<none>
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'OpGenerator:required_attrs' (1) due to: Could not load file or assembly 'protobuf-net, Version=2.3.2.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. assembly:protobuf-net, Version=2.3.2.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67 type:<unknown type> member:<none>

read: -p: no coprocess

[Process completed]

**Comment by migueldeicaza** [comment]
Odd looks like a problem on your end.

**Comment by RubyGemer** [comment]
What's the solution? @migueldeicaza you should atleast suggest me something :(
