### ISSUE TITLE
Avoid Using DecodeJpeg in Image Recognition

### ISSUE THREAD

**Issue by yjlintw** [migueldeicaza/TensorFlowSharp#155]
Hello, I've tried to run the ExampleInceptionInference on Unity on iOS/Android.
The example runs fine on Standalone, but it has error when running on iOS/Android. I think the reason might because mobile device does not support DecodeJpeg operation. Is there anyway I can modified the code so I don't need to use that operation? Thank you.

**Comment by migueldeicaza** [comment]
How are you running on mobile?   Did you ship your own native payload?  Because the NuGet package does not include those.

**Comment by yjlintw** [comment]
I was using the UnityTechnology ported TensorflowSharp
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity-(Experimental).md

**Comment by pudg** [comment]
Any update on this?

**Comment by migueldeicaza** [comment]
I do not support the mobile stack yet, this is an issue that should be filed against Unity for now.
