### ISSUE TITLE
Move to .NET Standard

### ISSUE THREAD

**Issue by ricebus** [migueldeicaza/TensorFlowSharp#158]
Hi,

I see that you library is targeted at .NET Framework but I've managed to compile it with .NET Core 2.0,
What do you think about re-targeting it so it'll have a bigger audience?

**Comment by migueldeicaza** [comment]
Yes, I love the idea.

I had not done it because VS2017.4 was not out, and I have had limited time since it did.

**Comment by kimbirkelund** [comment]
I need this to. If it has interest I'll be happy to try and cook up a PR?

**Comment by kimbirkelund** [comment]
I went ahead and started :-)

My progress can be seen here: https://github.com/migueldeicaza/TensorFlowSharp/compare/master...GameScorekeeper:feature/kim/netstandard?expand=1

Currently I have most of it working on Windows (haven't tried Linux yet, and have no access to Mac).

One of the Example projects couldn't be converted to .NET Core as it appears to use some of the missing System.Drawing APIs.

And one of the F# tests fails as of now. Haven't look closer into why. 

And there's probably some nuget packing issues - was a bit unsure how you packing process worked?


But other than that it is looking very promising.

**Comment by migueldeicaza** [comment]
Excellent work!

For System.Drawing, I suspect we can try to replace it with the new NuGet package that is being previewed:

https://github.com/dotnet/corefx/issues/20325

That said, perhaps we should just switch to SkiaSharp :-)

**Comment by migueldeicaza** [comment]
I realized something - the samples do not need to be moved to .NET Standard, only the library does

So the System.Drawing issue is a non-issue.

**Comment by kimbirkelund** [comment]
Yeah, as long as we don't need to build it on other than Windows.

**Comment by ddurschlag** [comment]
Is the publishing of a net standard 2.0 nuget package likely to happen soon? Is there anything I could do to help it along?

**Comment by migueldeicaza** [comment]
I need to merge the changes, might happen over the weekend or early next week.

**Comment by phillijw** [comment]
I'm also available to help and test.

**Comment by migueldeicaza** [comment]
Well, so I have a .NET standard 2 version of the library in a pull request, but I do not think I can convince travis CI to install both Mono and .net core on the same machine to try the code out, so the build would break and we would lose the CI.

**Comment by kimbirkelund** [comment]
Can't really find anything on it, and I assume you've already looked anyway, but I'd have thought that Mono and .NET Core could run side by side. They are after all just programs.

Unless you can stand up a separate CI server with .NET Core, you probably have to just jump in :-)

**Comment by ddurschlag** [comment]
Is the issue that you can't target Net Standard 2.0 or that you can't test
the resultant assembly against the .Net Core runtime?

**Comment by jmarti326** [comment]
I don't know if this issue has been resolved, but I would genuinely love to be able to use this library in .net core 2.0.  I tried to install the latest 1.4.0 nuget package but I got an error.

**Comment by ddurschlag** [comment]
I don't think it has. I'd happily use a .Net Standard 2.0-targeted version from dotnet core -- even if the automated tests were only running on mono (which I believe also supports .Net Standard 2.0 libraries) -- but it's not clear to me right now what I can do to help make that happen.

**Comment by migueldeicaza** [comment]
I updated the pull request with the help from @Dorokhov and I am hoping the next build gets us a netstadardad build.

Is it not a problem of living side-by-side, it works great at home, where I use this setup exactly.   .NET Standard libraries require .NET Core installed, and Mono is the runtime that runs it.   The issue was just with Travis CI that needed a small tweak to install both (and the fact that I am not very Travis savvy myself)

**Comment by migueldeicaza** [comment]
Update: we are currently tracking a bug in Mono, which prevents .NET Standard with Complex numbers from working on Mono when using .NET Standard, so I am going to wait for this fix to go live, it should be out soon, before we merge the .NET Standard support.

**Comment by migueldeicaza** [comment]
Shiping.
