### ISSUE TITLE
Nondeterministic behavior with variable init

### ISSUE THREAD

**Issue by boborp** [migueldeicaza/TensorFlowSharp#161]
Test code:

> using (var graph = new TFGraph())
>             {
>                 var W = graph.Variable(graph.Const((float)1.0));
>                 var b = graph.Variable(graph.Const((float)-1.0));
> 
>                 var x = graph.Placeholder(TFDataType.Float);
> 
>                 TFOutput m = graph.Mul(graph.ReadVariableOp(W, TFDataType.Float), x);
>                 TFOutput linear_model = graph.Add(m, graph.ReadVariableOp(b, TFDataType.Float));
> 
>                 float[] trainDataX = new[] { 1.0f, 2, 3, 4, 5, 7 };
> 
> 
>                 using (var sess = new TFSession(graph))
>                 {
>                     sess.GetRunner().AddTarget(graph.GetGlobalVariablesInitializer()).Run();
> 
>                     Console.WriteLine("res:");
>                     for (int i = 0; i < trainDataX.Length; i++)
>                     {
>                         var runner = sess.GetRunner();
>                         runner.AddInput(x, trainDataX[i]);
>                         runner.Fetch(linear_model);
> 
>                         var output = runner.Run();
> 
>                         foreach (var res in output)
>                         {
>                             Console.Write(res);
>                             Console.Write("\t");
>                         }
> 
>                         Console.WriteLine();
>                     }
> 
>                     Console.ReadKey();
>                 }
>             }
I believe this should compute y =W*x + b but instead of correct result: 0,1,2,3,4,6 I am getting either -2,-3,-4,-5,-6,-8 or 2,3,4,5,6,8 at random.
Please correct me if my sample is wrong.

**Comment by cesarsouza** [comment]
I suppose this is being caused by the problem described in #170, please see that issue for a workaround.

**Comment by boborp** [comment]
Thanks, the VariableV2 worked fine when using TF1.4. Thanks!
