### ISSUE TITLE
Performace question

### ISSUE THREAD

**Issue by sGambolati** [migueldeicaza/TensorFlowSharp#162]
I'm really noob in tensorflow and so, TensorFlowSharp. I tried the [ExampleObjectDetection](https://github.com/migueldeicaza/TensorFlowSharp/tree/master/Examples/ExampleObjectDetection) and noted that it take like 2 minutes to [return the output](https://github.com/migueldeicaza/TensorFlowSharp/blob/master/Examples/ExampleObjectDetection/Program.cs#L81). 

I tried to change to release mode and the time is almost the same. Is there anything I can do to boost performace?

Attached an image with time measured for important portion of code.
![image](https://user-images.githubusercontent.com/3267440/31519295-5e7d5e6e-af78-11e7-823f-2be6d5b51f38.png)

**Comment by gmlwns2000** [comment]
Use gpu for inferences will be helpful

**Comment by Dorokhov** [comment]
hi @sGambolati , please take a look at the table of available pre-trained models at the very bottom of this page:
https://github.com/tensorflow/models/blob/477ed41e7e4e8a8443bc633846eb01e2182dc68a/object_detection/g3doc/detection_model_zoo.md

by default, object detection samples downloads 'faster_rcnn_inception_resnet_v2_atrous_coco' model which is slow, as you can see from the table. You can switch to the other pre-trained model from the table, for instance, 'ssd_inception_v2_coco' which is fast (see instructions in the ObjectDetection example readme) or train your own model.

Hope it will help.

**Comment by sGambolati** [comment]
Thanks, @Dorokhov ! I'll give a try to change the model.
