### ISSUE TITLE
Is TFSession thread safe?

### ISSUE THREAD

**Issue by hanabi1224** [migueldeicaza/TensorFlowSharp#163]
What's the best practice to service TF model in web api, keep single TFSession instance without adding lock around it? Or creating object pool of TFSession if it's not thread-safe, thanks in advance!

**Comment by migueldeicaza** [comment]
That is a good question - I do not know the answer to that.

It really depends on the guarantees that TensorFlow provides, and I am not familiar with those.

**Comment by hanabi1224** [comment]
@migueldeicaza  thx, just posted a question in TF repo: https://github.com/tensorflow/tensorflow/issues/14146

**Comment by praeclarum** [comment]
TF documents as being thread safe:

> The TensorFlow Session object is multithreaded, so multiple threads can easily use the same session and run ops in parallel.

https://www.tensorflow.org/versions/r1.2/programmers_guide/threading_and_queues

In my experience, it works fine.
