### ISSUE TITLE
No constructor of TFTensor for string.

### ISSUE THREAD

**Issue by alexpantyukhin** [migueldeicaza/TensorFlowSharp#171]
I think it would be suitable to have ability for write something like:
```csharp
var tensor = new TFTensor("Hello, World")
```
I can implement this, if approved.

**Comment by migueldeicaza** [comment]
What is the type of the tensor?

Is that a single value that wraps a string (and if so, we need to sort out the encoding), or is it a vector of values in a particular encoding (same question)

**Comment by migueldeicaza** [comment]
Going to close the issue, as I do not think this is something that we need, specially given the open question above that is prone to sane people coming up with different interpretations.
