### ISSUE TITLE
Formatting & style

### ISSUE THREAD

**Issue by cesarsouza** [migueldeicaza/TensorFlowSharp#179]
Hi @migueldeicaza,

While I am aware of the project instance against unilateral uneccessary code refactorings (e.g. #39) and I mostly agree with them, I have to say that some files would indeed benefit from at least some code style normalizations to at least enforce consistency. Right now, in the same file, it is possible to find multiple bracket styles being used (e.g. [K&R](https://github.com/migueldeicaza/TensorFlowSharp/blob/master/TensorFlowSharp/Tensorflow.cs#L54) and [Allman's](https://github.com/migueldeicaza/TensorFlowSharp/blob/master/TensorFlowSharp/Tensorflow.cs#L125)), indentation using both [spaces and tabs](https://github.com/migueldeicaza/TensorFlowSharp/blob/master/TensorFlowSharp/Tensorflow.cs#L1033-L1039), and different [rules](https://github.com/migueldeicaza/TensorFlowSharp/blob/master/TensorFlowSharp/Tensorflow.cs#L1595) [regarding](https://github.com/migueldeicaza/TensorFlowSharp/blob/master/TensorFlowSharp/Tensorflow.cs#L2379) spaces.

I know this is minimal, but if you allow me I could at least enforce the .editorconfig style I had created a while ago to solve those inconsistencies - then at least, everyone else using VS2017 would have been able to enforce the same formatting style when hitting Ctrl+E,D (or Ctrl+K, D).

**Comment by migueldeicaza** [comment]
Could you share that editor config?

**Comment by cesarsouza** [comment]
It's already in the project, [.editorconfig at the repo's root](https://github.com/migueldeicaza/TensorFlowSharp/blob/master/.editorconfig).

**Comment by migueldeicaza** [comment]
Ah got it - I have noticed that some different styles have creeped up, which files in particular have this problem?

**Comment by migueldeicaza** [comment]
(I do most of my work from home, on Visual Studio for Mac, that currently lacks support for `.editorconfig`, so I might be guilty to some extent for some of those)
