### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by darkoob12** [migueldeicaza/TensorFlowSharp#192]
I have employed _TensorFlowSharp_ in my windows application but after a few hours the application takes all of my memory.
I guessed that I am not disposing the objects correctly so I mimiced the example projects and put all `TFGraph` and `TFSession` in `using` blocks. but that did not helped.

So i changed the __ExampleObjectDetection__ project in the following way:
loads the model and run it on the same image 2000 times.
``` C#
var sw = System.Diagnostics.Stopwatch.StartNew();
using (var graph = new TFGraph()) {
    var model = File.ReadAllBytes(modelFile);
    graph.Import(new TFBuffer(model));
    sw.Stop();
    Console.WriteLine($"model is loaded - time : {sw.ElapsedMilliseconds} ms");
    for (int i = 0; i < 2000; i++) {
        using (var session = new TFSession(graph)) {
            sw.Restart();
            foreach (var tuple in fileTuples) {
                var tensor = ImageUtil.CreateTensorFromImageFile(tuple.Item1, TFDataType.UInt8);
                var runner = session.GetRunner();


                runner
                    .AddInput(graph["image_tensor"][0], tensor)
                    .Fetch(
                    graph["detection_boxes"][0],
                    graph["detection_scores"][0],
                    graph["detection_classes"][0],
                    graph["num_detections"][0]);
                var output = runner.Run();

                var boxes = (float[,,])output[0].GetValue(jagged: false);
                var scores = (float[,])output[1].GetValue(jagged: false);
                var classes = (float[,])output[2].GetValue(jagged: false);
                var num = (float[])output[3].GetValue(jagged: false);

                DrawBoxes(boxes, scores, classes, tuple.Item1, tuple.Item2, MIN_SCORE_FOR_OBJECT_HIGHLIGHTING);
            }
            sw.Stop();
            Console.WriteLine($"run # {i} - time : {sw.ElapsedMilliseconds} ms");
        }
    }
}
```
this is how memory increases on my laptop.
![image](https://user-images.githubusercontent.com/1968642/33988694-59d460b8-e0da-11e7-88e9-1a56a166f9fe.png)

If anyone has experienced this behavior, please tell me how i can fix it.
Thanks.

**Comment by migueldeicaza** [comment]
Can you provide either a complete sample, so I can run it on a profiler, or run the code with a profiler and track down which object instances are being kept alive?

**Comment by rogihee** [comment]
Var output is an array of Tensors which you need to call Dispose() on.

**Comment by darkoob12** [comment]
Sorry for late response.
Thanks @rogihee . That was the problem. I quit the habit of using vars everywhere, now i know type of all my variables and which one of them need disposing.
