### ISSUE TITLE
Multi Core or Multi Thread

### ISSUE THREAD

**Issue by DanielChowHL** [migueldeicaza/TensorFlowSharp#196]
Hi,
This project is so great, efficient.
But I have a question:
Can TensorflowSharp run with multi core or multi thread without any interception?
I tried to run TFS in multi threads or multi applications, but I found the threads were blocked.
thanks.

**Comment by migueldeicaza** [comment]
I do not know what "interception" means.

TensorFlowSharp is a binding around TensorFlow, so generally, the limitations of the upstream technology apply.   It is best to pose this question to the upstream project.
