### ISSUE TITLE
can tensorflowsharp load model which trained by python？ 

### ISSUE THREAD

**Issue by flyzaway** [migueldeicaza/TensorFlowSharp#200]
hello, thanks for your excellent code, and i have a question, if i trained a tensorflow model by python and save it, can tensorflowsharp load it and use this model to predict?

**Comment by IlSaCCo** [comment]
Yes you can, you can use the sample code that comes with the project. You just have to change the pb file you load.
The only problem I am dealing with at the moment are the different results you get when using the protobuf in python and in c#
[https://github.com/migueldeicaza/TensorFlowSharp/issues/191](url)

**Comment by migueldeicaza** [comment]
Thanks for the answer @IlSaCCo!
