### ISSUE TITLE
Xamarin.Mac not supported

### ISSUE THREAD

**Issue by praeclarum** [migueldeicaza/TensorFlowSharp#202]
The README says mac is supported but the package cannot be installed for Xamarin.Mac.

If you switch away from Xamarin.Mac and use the unsupported (and very large) .NET profile, then it almost works - it still puts the delis in the wrong place.

It would be nice if this library worked on Mac...

**Comment by migueldeicaza** [comment]
Godo point, I will look into it.

I started just with the desktop profile, as it was easy to test, there are two pull requests that move this to .NET standard 2, which would both address the Xamarin.Mac issue and make this work with .NET Core.

My only reservation with the patches is (a) my attempt failed, for reasons I do not understand yet; and (b) the contributed pull request has too many chances beyond the library and I am not sure I want to take that patch.

**Comment by migueldeicaza** [comment]
New packages work out of the box.
