### ISSUE TITLE
Memory leak in example ImageUtil.cs 

### ISSUE THREAD

**Issue by micoene** [migueldeicaza/TensorFlowSharp#212]
The imageUtil class in Tensorflowsharp/Examples/ExampleCommon/ImageUtil.cs gives a memory leak as example.
The graph object made in ConstructGraphToNormalize is not disposed in the createTensorFromImageFile method.

Proposed change : 

from : 

```
using (var session = new TFSession (graph)) {
				var normalized = session.Run (
						 inputs: new [] { input },
						 inputValues: new [] { tensor },
						 outputs: new [] { output });
				return normalized [0];
			}

```

To : 

```
using (var session = new TFSession (graph)) {
				var normalized = session.Run (
						 inputs: new [] { input },
						 inputValues: new [] { tensor },
						 outputs: new [] { output });
                                inputData.Dispose(); //optional, depending on how the rest of the code is
                                graph.Dispose(); //nessesary, gave a huge memory leak with large images
				return normalized [0];
			}
```

**Comment by migueldeicaza** [comment]
Thanks for debugging this, a PR has been submitted:

https://github.com/migueldeicaza/TensorFlowSharp/pull/213

**Comment by micoene** [comment]
You're welcome :), and thanks !
Maybe its a good idea to put a comment above the using statement saying that not disposing graph elements (or encapsulate them in a using statement) makes it unreachable for the garbage collector.

**Comment by migueldeicaza** [comment]
It is not unreachable, it is just that the GC has chosen not to collect that object yet, as it has no clue that an innocent looking pointer (8 bytes) is actually holding the keys to megabytes of data behind it.

This is a common issue with bindings and GC languages.
