### ISSUE TITLE
how to pass 1-D String array to .pb model 

### ISSUE THREAD

**Issue by fanyuguang** [migueldeicaza/TensorFlowSharp#216]
I use TensorflowSharp to load .pb model. I need create 1-D String array Tensor, then pass it into .pb model. Anyone knows how to do it, thanks

**Comment by fanyuguang** [comment]
below is my code
![image](https://user-images.githubusercontent.com/32627471/35371135-515b1472-01cd-11e8-8876-4834201db764.png)
![image](https://user-images.githubusercontent.com/32627471/35371158-64ab074e-01cd-11e8-8eec-28b224b81fa6.png)

**Comment by migueldeicaza** [comment]
I suspect you want `TFTensor.CreateString`, but it is hard to tell from your question, there is just not enough information to guess.

The docs mention this:

https://migueldeicaza.github.io/TensorFlowSharp/api/TensorFlow/TensorFlow.TFTensor.html
