### ISSUE TITLE
TensorFlowSharp 1.5.0-pre2 supports UWP x64!

### ISSUE THREAD

**Issue by MrMYHuang** [migueldeicaza/TensorFlowSharp#217]
I find TensorFlowSharp 1.5.0-pre2 supports UWP x64! Thanks to TensorFlowSharp 1.5.0-pre2 supports .NET Standard 2.0, now UWP x64 apps (TargetPlatformMinVersion UAP 10.0.16299.0) can install the TensorFlowSharp nuget package and run TensorFlow.

I have tried the constant multiplication test program in README.md. It works. Thanks to TensorFlowSharp developers.

Finally, I hope TensorFlowSharp supports more CPU architectures in the future, e.g., Win x86 and Win ARM. Thanks.

**Comment by MrMYHuang** [comment]
I tried to build x86 tensorflow.dll by [this](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake). Unfortunately, finally, I achieved a place that there were many compilation errors like
```conversion from int64 to int requires a narrowing conversion```
It seems TensorFlow has no official support for 32-bit compilation. People might not waste time on trying to compile x86 tensorflow.dll, isn't it?

**Comment by migueldeicaza** [comment]
TensorFlowSharp requires 64 bits, even if you ever managed to compile the underlying runtime as 32.

**Comment by MrMYHuang** [comment]
I see. Thanks.

**Comment by weizhuang-93** [comment]
so its not possible to get TF# to run on UWP?
