### ISSUE TITLE
Argmax does not seem to be recognized in TensorFlowSharp

### ISSUE THREAD

**Issue by lagidigu** [migueldeicaza/TensorFlowSharp#219]
I've been trying to include a Tensorflow byte graph into unity, but I get the error that the function argmax is not recognized. 

Currently using Tensorflow 1.4.1.

Is there a solution to this?

**Comment by migueldeicaza** [comment]
Please provide a sample showing the issue, I do not quite follow.

At least on 1.5, there is this API on `TFGraph`:

```csharp
public TFOutput ArgMax (TFOutput input, TFOutput dimension, TFDataType? output_type = null, string operName = null)
```
