### ISSUE TITLE
An unhandled exception of type 'System.BadImageFormatException' occurred in TensorFlowSharp.dll

### ISSUE THREAD

**Issue by DomLi** [migueldeicaza/TensorFlowSharp#22]
Dear Sir,
Thank you for  your wonderful work on Tensorflowsharp. I tried to run ExampleInceptionInference project  following your guides,  successfully obtain libtensorflow.dll under linux, and copy this model to debug folder under x64 of visual studio 2015 , after success with compiling/building work done, when ran "Tensorflow.cs" up to 
public TFGraph () : base (TF_NewGraph ())
		{
		}
following exception message occured: 
"An unhandled exception of type 'System.BadImageFormatException' occurred in TensorFlowSharp.dll
Additional information: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"
could you please kindly fix it and help to point it out where I did wrong?
thank you very much indeed!

**Comment by migueldeicaza** [comment]
You need to get a native build of libtensorflow.dll for Windows for this to work

TensorFlowSharp.dll is the managed code (the cross platform code) which calls into the native code (libtensorflow.dll).   So you do need to build the latter on Windows for this to work.

**Comment by DomLi** [comment]
Hi Miguel,

Thank you very much for your kind reply, and I will have look at it on how
to build up libtensorflow.dll directly on windows 7.
At moment , i don't have much idea yet, will really appreciate if you can
give a clue .

Have good day and weekend,
Take care, will back to bother you later.😄😅😊

regards,
Dom

**Comment by migueldeicaza** [comment]
Hello,

You can try this command to build on Windows:

bazel build -c opt //tensorflow/tools/lib_package:libtensorflow.tar.gz

**Comment by DomLi** [comment]
Hi Miguel,

Again, many thanks/
I tired this command above under oracle VM VirtuBox with ubuntu 1.6  at
~/tensorflow/tools$

 but got message like:

........................
INFO: Found 1 target...
Target //tensorflow/tools/lib_package: libtensorflow.tar.gz up-t-date:
bazel - bin/tensorflow/tools/lib_package/libtensorflwo.targ.gz
INFO: Elapsed time: 74.438s, Critical Path: 39.37s

then after, I lost idea that what I should do next ...
please help me some more.

thanks lot

regards,
Dom

**Comment by cesarsouza** [comment]
Hi Dom Li,

I think that Miguel's suggestion was to run that given command in a PowerShell environment within Windows itself, not exactly under VirtualBox. You might [need to install bazel through Chocolatey first](https://chocolatey.org/packages/bazel), though. 

Regards,
Cesar

**Comment by luketg8** [comment]
Hi,

I tried this. What happens is you need to run ./configure in the TensorFlow repository before you can build this shared libraries. This presents issues in that every time it got past the 'Python Libraries stage' it would simply restart. This has been frustrating as I know my Bazel build for windows works as I tried building some examples, so it just seems like another hurdle to get over!

**Comment by Aminullah6264** [comment]
hi,
i getting the same error 

System.BadImageFormatException occurred
  HResult=0x8007000B
  Message=Could not load file or assembly 'TensorFlowSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

i have both dll files build in my project TensorFlowSharp.dll and libtensorflow.dll

this is my code, could anyone help me to solve this problem 
i really problematic for this

 try
            {
                var graph = new TFGraph();
                // Load the serialized GraphDef from a file.
                var model = File.ReadAllBytes("D:\\Projects\\ImageROICollection\\ImageROICollection\\overfeat_rezoom_2017_07_15_12.51\\save.ckpt-10000");
                graph.Import(model, "");
                using (var session = new TFSession(graph))
                {
                    var tensor = CreateTensorFromImageFile(filesName[mainIndex]);
                    var runner = session.GetRunner();
                    runner.AddInput(graph["input"][0], tensor);
                    runner.Fetch(graph["output"][0]);

                    var output = runner.Run();

                    // Fetch the results from output:
                    TFTensor result = output[0];
                    MessageBox.Show(result.ToString());

                }
            }
            catch(Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }

**Comment by Aminullah6264** [comment]
hi,
i getting the same error

System.BadImageFormatException occurred
HResult=0x8007000B
Message=Could not load file or assembly 'TensorFlowSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

i have both dll files build in my project TensorFlowSharp.dll and libtensorflow.dll

this is my code, could anyone help me to solve this problem
i really problematic for this

try
{
var graph = new TFGraph();
// Load the serialized GraphDef from a file.
var model = File.ReadAllBytes("D:\Projects\ImageROICollection\ImageROICollection\overfeat_rezoom_2017_07_15_12.51\save.ckpt-10000");
graph.Import(model, "");
using (var session = new TFSession(graph))
{
var tensor = CreateTensorFromImageFile(filesName[mainIndex]);
var runner = session.GetRunner();
runner.AddInput(graph["input"][0], tensor);
runner.Fetch(graph["output"][0]);

                var output = runner.Run();

                // Fetch the results from output:
                TFTensor result = output[0];
                MessageBox.Show(result.ToString());

            }
        }
        catch(Exception ex)
        {
            MessageBox.Show(ex.ToString());
        }

**Comment by sayfee** [comment]
I know it's been a while since someone posted on this thread, but I wanted to point out that if you just go to project/properties/build and use 64bits, that should fix the issue

**Comment by Biirra** [comment]
Good work sayfee That worked like a charm.
