### ISSUE TITLE
BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

### ISSUE THREAD

**Issue by qdraw** [migueldeicaza/TensorFlowSharp#222]
Hello,
I'm trying to get the TensorFlowSharp to work on Azure, but for some reason I hit a System.BadImageFormatException.

I'm using version 1.5 from TensorflowSharp and the dll's that are included.
![schermafbeelding 2018-02-12 om 17 27 14](https://user-images.githubusercontent.com/1826996/36107347-0427f9b2-101a-11e8-9d37-8d6927f76f4c.png)
On my local machine Windows 10 VS2017 the setup works. .NET Core 2

**Comment by qdraw** [comment]
I already found out that on Azure the default .net core is x86-64 and on my local machine it is x64 https://blogs.msdn.microsoft.com/webdev/2018/01/09/64-bit-asp-net-core-on-azure-app-service/
I create a full build:
`$ dotnet publish -c release -r win-x64 `
copy the files from `/bin/Release/netcoreapp2.0/win-x64/publish/`

**Comment by jonathanantoine** [comment]
Sorry for asking @qdraw but to be sure : your solution is to force and use the x64 version and deploy it instead of an "Any CPU"  version?

**Comment by qdraw** [comment]
@jonathanantoine Yes, I havn't tested this recent again but on Azure make sure that is running on x64 mode instead of x86. One year ago this solves my issue.

**Comment by jonathanantoine** [comment]
OK thanks for your reply. My issue was in fact related to something else.

**Comment by linehammer** [comment]
The exception that is thrown when the file image of a dynamic link library (DLL) or an executable program is invalid. If you get a BadImageFormatException when interfacing with a native DLL, it almost always means that you are trying to interface with a 32-bit DLL while running in the 64-bit CLR, or vice versa. IN most cases you might be  facing the problem with your website after deploying on server. 

Make sure that you are not having 32-bit / 64-bit conflict. So, you need to adjust your application pool to Enable 32-Bit  or 64-Bit accordingly. Set the Target platform setting on your [c#](http://net-informations.com/faq/default.htm) EXE project, not your class library project. Alternatively, you can ship both 32-bit and 64-bit DLLs with different file names, define separate P/Invoke stubs for each version, and decide which one to call at runtime. The easiest way to do this would probably be to wrap your native calls in an interface (e.g., INativeMethods) and choose which implementation to instantiate at runtime based on IntPtr.Size. With this method, you could still target AnyCPU.
