### ISSUE TITLE
[HOWTO] Works on Windows Dev machine, not on clean installed server

### ISSUE THREAD

**Issue by Teun** [migueldeicaza/TensorFlowSharp#226]
OS: Windows 10, Windows 2012 R2, .NET 4.7.1
When I install TensorFlowSharp using the VS2017 package manager on my dev box it works fine (with 1.4.0, for 1.5.0 I have to manually copy the libtensorflow.dll). I run my tests on .NET 4.7.1. Then, I want to do some tests on a production-like machine, so I spin an AWS instance running Windows (Windows_Server-2012-R2_RTM-English-64Bit-Base-2018.01.12 ami-cc821eb5) and copy the binaries over, including the libtensorflow.dll. Now, when I run my application, it immediately throws an exception: Unable to load DLL 'libtensorflow'.

Version of .NET is exactly identical. Both tests runs as Administrator

I think maybe some other component is installed on my dev box and not on that clean server. Any ideas?

**Comment by Teun** [comment]
Also tried on Windows 2016. Same result.

**Comment by Teun** [comment]
I found the problem: the nuget package requires the Microsoft Visual C++ 2015 Redistributable to be installed on the machine. I guess this is often already the case, but not on a clean machine. Installer to be found here fixed it for me: https://www.microsoft.com/en-us/download/details.aspx?id=53840

Maybe it should be included in the package? Will leave this open for some time to allow for comments. Will close otherwise.

**Comment by migueldeicaza** [comment]
Thanks for providing the solution to the problem, I do not think at this time that I want to ship that runtime.

**Comment by Teun** [comment]
Yes, I see why you wouldn't want that.

**Comment by ioanghi** [comment]
I have the same problem. On my developer PC it runs, on a clean machine without VS it does not run. Even after I installed the Visual C++ Redistributables 2015 14.0.24215 as described above.
Any idea what are all dependencies of libtensorflow.dll ?
