### ISSUE TITLE
Support for UWP

### ISSUE THREAD

**Issue by Pooja-B** [migueldeicaza/TensorFlowSharp#233]
Hi, 
I tried using the library with UWP app as I wanted to create an Universal app to run on my raspberry pi board but it is failing to install through Nuget. Any possibilities for this?
Any help would be highly appreciated.
Thanks,
Pooja

**Comment by migueldeicaza** [comment]
It might be possible, but there are some challenges, the first one is getting the native TensorFlow library to compile under UWP, if you can get that compiled, then we can move on to the next stage which would be to try this out.

In the meantime, you could try TensorFlow + Raspberri on Linux
