### ISSUE TITLE
[Object Detection Example]Example project not compiling on Visual Studio 2015 .NET 4.6.1 Windows 10

### ISSUE THREAD

**Issue by funkysandman** [migueldeicaza/TensorFlowSharp#237]
Hi, I'm having no luck compiling the exampleObjectDetection project.  The exampleCommon project compiles fine.  I've upgraded all the nuget packages and everything looks good, all references appear to be ok.  I'm targeting .NET 4.6.1.  Here's a snapshot of the compile error:
![example_error](https://user-images.githubusercontent.com/37027650/37183698-5c1fe4a6-2305-11e8-9b0d-711ac798cb13.PNG)

any ideas?

**Comment by funkysandman** [comment]
I upgrade to Visual Studio 2017 and I was able to compile

**Comment by Dorokhov** [comment]
Thanks, @funkysandman  for sorting it out. Really, that example has a dependency on C# compiler version allowing tuples.

**Comment by migueldeicaza** [comment]
Correct - you need a newer version of the language.
