### ISSUE TITLE
How to get string output from TFTensor?

### ISSUE THREAD

**Issue by edwardyehuang** [migueldeicaza/TensorFlowSharp#238]
@After I get TFTensor output from the session.run. I am not able to convert it to string. The TFTensor.GetValue() for string is not implemented.

So how to solve this problem?

**Comment by edwardyehuang** [comment]
Currently, I am using Marshal.Copy + Encoding.UTF8.GetString to get the string from "TFTensor.Data". Any better way to do this?

**Comment by YanYas** [comment]
Indeed, I understand that there is a Tensor string type in tensorflow but I think it is only used for passing arguments for system operations such as file names and serializing graph info. For your own strings they have to be handled explicitly as you had done. 
Maybe in the future this will become easier, but I'm not privvy to those conversations.

**Comment by edwardyehuang** [comment]
@YanYas  String will be useful when need to return a string result, such as an OCR model.

**Comment by ghulammustufa31** [comment]
@edwardyehuang did you find a solution to this problem? I am having the same issue.

**Comment by edwardyehuang** [comment]
> 
> 
> @edwardyehuang did you find a solution to this problem? I am having the same issue.

Yea, please read my reply on 9 Mar 2018. However, I am not sure if there is a better way now.

**Comment by migueldeicaza** [comment]
Merged the fix.

**Comment by pn12** [comment]
@migueldeicaza - what is the method to extract ?
