### ISSUE TITLE
Can this API be used to create a tensorflow serving client in tensorflow servings?

### ISSUE THREAD

**Issue by R-Miner** [migueldeicaza/TensorFlowSharp#250]
Instead of installing python in my client windows machine, can I use this tensoflowsharp API to write a client program to call the ternsorflow servings servable?

**Comment by migueldeicaza** [comment]
I do not know what the "servings servable" is.

While you can use TensorFlowSharp to build TensorFlow applications with .NET, I strongly recommend that you have the Python version installed as so much of the tensorflow ecosystem relies on it.
