### ISSUE TITLE
[Object Detection Example] missing libtensorflow

### ISSUE THREAD

**Issue by Barsonax** [migueldeicaza/TensorFlowSharp#254]
The libtensorflow.dll is missing but its not explained where to get this file.

**Comment by migueldeicaza** [comment]
The main page instructs you to get a NuGet package that contains the payload:

```
nuget install TensorFlowSharp
```

And the contriubuting file describes how to set up your environment:

https://github.com/migueldeicaza/TensorFlowSharp/blob/master/CONTRIBUTING.md
