### ISSUE TITLE
TensorFlow csharp api question

### ISSUE THREAD

**Issue by RevoluPowered** [migueldeicaza/TensorFlowSharp#259]
I'm interested in potentially using this on a production system, but I am in the research phase of my project at the moment.

The thing which interests me is GPU and CPU support, is this available in tensor flow csharp or is it untested at the moment?

Also, is dot net core 2.x supported?

Thanks,
Gordon

**Comment by jefflomax** [comment]
Gordon,

I just quickly ported ExampleObjectDetection to .NET Core 2.0 and it ran just fine.  All I actually had to do was to add a library to provide the GDI+ graphics (Install-Package System.Drawing.Common -Version 4.5.0-preview2-26406-04)

**Comment by truencoa** [comment]
Same.  We have a bunch of ports with no issue.  Please close this or post a specific question or example.
