### ISSUE TITLE
How to build cloned repo

### ISSUE THREAD

**Issue by JacobChrist** [migueldeicaza/TensorFlowSharp#263]
I've been lurking this repo for some time and have slowly been trying to use it.  Only after several hours of confusion and frustration spread out over several weeks have I been able to get the cloned repo to compile.  My biggest issue was that I was trying to use VS2015 CE to build the cloned repo.  It wasn't until I read the CONTRIBUTING.md  that I figured out that I needed to use VS2017 (I'm using CE).  It took me such a long time to find this because I figured that if I couldn't compile the project I'm not ready to start contributing.  It would be nice if information on how to build the cloned repo was before the section on working with the samples.

On a positive note I have previously pulled in TensorFlowSharp into existing VS2015 projects using NuGet because the readme.md file clearly tells how to do this (thought I haven't done anything with it yet).

**Comment by truencoa** [comment]
Why are you not using VS2017 CE?  The fixes go well beyond what's included in this project.

**Comment by JacobChrist** [comment]
I am now.  I think my point was that it was not clear that I needed to use VS2017.

**Comment by migueldeicaza** [comment]
Updated README.
