### ISSUE TITLE
TFSharp with GPU

### ISSUE THREAD

**Issue by weirdobeardo48** [migueldeicaza/TensorFlowSharp#267]
Hi, 

I have built my own libtensorflow.dll file from source with cmake on window to make it work with my project since I can't find it anywhere on the Internet. 

But it throws an Exception:

`Exception: Exception thrown: 'System.DllNotFoundException' in TensorFlowSharp.dll ("Unable to load DLL 'libtensorflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"). Exception thrown: 'System.DllNotFoundException' in TensorFlowSharp.dll ("Unable to load DLL 'libtensorflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)")	`

In case some one need my dll, here is the link: [https://1drv.ms/u/s!AkYTnh_LTASRhCnCIxEks7CXIgKr](url)
I built it from r1.5, and I'm using TensorFlowSharp from NugetPackage ver 1.5. 

Please give me some advice, what I did wrong or what should I do to make it work then?

Sorry for my bad English.

**Comment by edwardyehuang** [comment]
Make sure you included the cudnn dll in the system path (or directly included with your exe). The cudnn dll must be the one you build the tensorflow
