### ISSUE TITLE
TensorFlowSharp API Question: How to get a tensor by name

### ISSUE THREAD

**Issue by samueljlopes** [migueldeicaza/TensorFlowSharp#274]
Hi everyone, 
In the Python code that I am trying to move over to C#, it references an 'Output Node', like this;
    `output_node = tf.get_default_graph().get_tensor_by_name(name=FLAGS.output_node_names)`

How would I replicate this in TensorFlowSharp? My model is saved and stored in a .bytes file (I'm using it in Unity). Thanks.

**Comment by lonk1999** [comment]
TensorflowSharp uses the model of.Pb file, usually I turn the model into.Pb file in Python, this process seems to be called "model persistence".

If you already have the.Pb model file, you can print out the graph and see what the name of the output node is.

**Comment by lindyrock** [comment]
@samueljlopes did you ever figure out how to do this?  I am trying to do the same.

**Comment by oferbentovim** [comment]
its not all you need but this is how far i  could go (still looking for my outputs)
`
static public void AnalyzeGraphOpperations(TFGraph graph)
        {
            bool echo = false;
            bool echo2 = true;
            int n = 0;
            string result = "";
            List<TFOperation> PlaceHoldersList = new List<TFOperation>();
            List<TFOperation> VarsList = new List<TFOperation>();
            List<TFOperation> outputListmaybe = new List<TFOperation>();
            List<string> optypelist = new List<string>();
            
            IEnumerable<TFOperation> tfgrph =  graph.GetEnumerator(); // get graph enumerator
            foreach (TFOperation op in tfgrph)
            {
                n++;
                if (echo) result += n + " " + op.OpType + "\t" + op.Name + " \n";
                if (op.OpType == "Placeholder") PlaceHoldersList.Add(op); // i think these are the inputs to the graph - mainly image
                if (op.OpType == "Variable" || op.OpType == "VariableV2") VarsList.Add(op);

                TFOperation[] oplist = op.ControlOutputs;
                if (oplist.Length > 0)
                {
                    result += (n + " " + op.OpType + " \t" + op.Name + "\n");
                    if (op.OpType == "Const" || op.OpType == "Assign" || op.OpType == "NoOp" || op.OpType == "Placeholder") result += "maybe but not likly output\n";
                    else
                    {
                        outputListmaybe.Add(op);
                        foreach (TFOperation opad in oplist)
                        {
                            result += "\t\t\t" + opad.OpType + "\t" + opad.Name + "\n";
                        }
                    }
                }
            }
            if (echo2)
            {
                if (PlaceHoldersList.Count > 0)
                {
                    result += "\nPlaceholders\n";
                    foreach (TFOperation pl in PlaceHoldersList) result += pl.OpType + "\t" + pl.Name + " \n";
                }
                else result += "\ncould not find input placeholders\n";

                if (VarsList.Count > 0)
                {
                    result += "\nVariable and VariableV2\n";
                    foreach (TFOperation pl in VarsList) result += pl.OpType + "\t" + pl.Name + " \n";
                }
                else result += "\nCould not find Variable or VariableV2\n";

                if (outputListmaybe.Count > 0)
                {
                    result += "\nThese may be my output\n";
                    foreach (TFOperation pl in outputListmaybe) result += pl.OpType + "\t" + pl.Name + " \n";
                }
                else result += "\nCould not find outputs\n";
            }
`
