### ISSUE TITLE
Why did TensorflowSharp return to different results?

### ISSUE THREAD

**Issue by lonk1999** [migueldeicaza/TensorFlowSharp#275]
The same model was used to detect the same picture and linear regression to get different results.

1.	Ubuntu14.04 + Python 3.5 + tensorflow 1.2 GPU
type：python testpb.py
result：871.58215
![image](https://user-images.githubusercontent.com/25821469/40161068-26aa7dc2-59e2-11e8-8bd2-e91620068a51.png)

2.	Windowns 7 + python 3.5 + tensorflow 1.4 CPU
type：python testpb.py
result：871.58221436
![image](https://user-images.githubusercontent.com/25821469/40161186-8bcc261a-59e2-11e8-9154-3cf225df7ed7.png)

3.	Vs2017 + TensorFlowSharp (1.2、1.4、1.7)
Project：TensorFlowSharp-master\Examples\ExampleInceptionInference
Input：graph ["input/X"] [0] —— 1* 250 * 250 * 1
Output：graph ["FullyConnected/BiasAdd"] [0]——1 * 1，float
Result：62814.1328
![image](https://user-images.githubusercontent.com/25821469/40161304-ea889c42-59e2-11e8-848a-6aef901c92d8.png)

**Comment by lonk1999** [comment]
I don't know where the mistake happened. I really need your help.

**Comment by migueldeicaza** [comment]
Not possible to debug this without the full python and c# code.

Ideally, you need to make a smaller reproducible test case to isolate the problem.  Reopen the bug when you have that.
