### ISSUE TITLE
Op type not registered 'ClipByValue' in binary

### ISSUE THREAD

**Issue by zsong** [migueldeicaza/TensorFlowSharp#276]
When I load the graph, I got this error:

Op type not registered 'ClipByValue' in binary running on [machine]. Make sure the Op and Kernel are registered in the binary running in this process.

I am on TensorflowSharp 1.7.0 with .Net 4.6.2.

**Comment by migueldeicaza** [comment]
Where did you get this model from?

**Comment by zsong** [comment]
This is what I converted from Keras model with this converter [https://github.com/amir-abdi/keras_to_tensorflow]

**Comment by abhimohta** [comment]
Getting the same error. 

Details: Built a LSTM based model using TF, used freeze_graph to make is usable with TFSharp, but on trying to import the graph, get this error. I used the last comment in [this](https://stackoverflow.com/questions/45466020/how-to-export-keras-h5-to-tensorflow-pb) to generate the .pb file.

**Comment by alex-zu** [comment]
'ClipByValue' appeared in TF since v1.8 (ie you trained the model on this version), but TensorflowSharp 1.7.0 include TF v1.7

**Comment by migueldeicaza** [comment]
Got it, so this is a matter that requires the release of 1.8, will have to look at that.

**Comment by migueldeicaza** [comment]
I have published a 1.8.0-pre1 nuget package, please reopen the bug if this is not fixd there.
