### ISSUE TITLE
Importing to Unity

### ISSUE THREAD

**Issue by pudg** [migueldeicaza/TensorFlowSharp#278]
Managed to get the bindings to kinda work within Unity3D. The example that adds to integers runs fine but when trying to import an pretrained model I keep getting errors such as
`TFException: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray_2 = TensorArrayV3[clear_after_read=true, dtype=DT_INT32, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name=""](Preprocessor/map/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
TensorFlow.TFStatus.CheckMaybeRaise (TensorFlow.TFStatus incomingStatus, System.Boolean last) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFGraph.Import (TensorFlow.TFBuffer graphDef, TensorFlow.TFImportGraphDefOptions options, TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFGraph.Import (System.Byte[] buffer, TensorFlow.TFImportGraphDefOptions options, TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFGraph.Import (System.Byte[] buffer, System.String prefix, TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
importer.Start () (at Assets/importer.cs:22)
`
I've looked around, trained and exported my graph using different CPU tensorflow versions (1.4.0 - 1.8.0) GPU Tensorflow was giving errors along the lines of "make sure GraphDef reader is compatible with GraphDef generator". Help/resources would be greatly appreciated.

**Comment by migueldeicaza** [comment]
You probably want to use the version that Unity has forked and maintains.

**Comment by ip** [comment]
@migueldeicaza Don't you want to backport their changes?
