### ISSUE TITLE
Unity Debug.Log for Speech Command TensorFlow Example 

### ISSUE THREAD

**Issue by nadir500** [migueldeicaza/TensorFlowSharp#285]
hello 
i need help with accessing the names of inputs and outputs of the SpeechCommand TensorFlow Example Model like how can i log the model when i import it to a graph object in unity like this: 

```
   TextAsset model = Resources.Load("GoStop") as TextAsset;
        Debug.Log("ss");
        Debug.Log("First Byte " + model.bytes[0]);
         TFGraph  graph = new TFGraph();
         graph.Import(model.bytes);
```
then needs to know the model inputs and outputs which is not described in the TensorFlow speechCommands Example...please help.

**Comment by migueldeicaza** [comment]
If this is related to the Unity port, it would be best to post on the Unity forums.
