### ISSUE TITLE
RunOptions

### ISSUE THREAD

**Issue by IlSaCCo** [migueldeicaza/TensorFlowSharp#291]
I have been looking on the documentation, on stackoverflow and on the net but I cannot find a sample snippet about how to correctly set TFBuffer runOptions/runMetadata parameter in session.Run.

`var normalized = session.Run(   
   inputs: new[] { input },
   inputValues: new[] { tensor },
   outputs: new[] { output },
   runMetadata: ##WhatDoIPutHere?##,
   runOptions: ##WhatDoIPutHere?##
);`

I saw that in Python API something like the following is possible:
`options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)`
I was wondering if that is possible in TFSharp too

I am trying to profile my object detection application as I am far away from my target speed (running realtime), I am hoping to see how the graph perform at infere time. Any suggestions are welcome

**Comment by migueldeicaza** [comment]
You need to pass a protocol-buffer encoded data, for metadata this is the protocol buffer

https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/core/protobuf/config.proto

For options, you use this protocll buffer:

https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/core/protobuf/config.proto

I have updated the API docs with this information.

**Comment by MindMusic** [comment]
I'm having problems with this too... I too am trying to optimize for speed... I too am unable to find any C# examples of how to enable FULL_TRACE.  Has anyone had success with this?

**Comment by hillin** [comment]
@migueldeicaza what is the correct way to pass a `RunMetadata` to a `TFSession.Runner`? The following code:
```
var runner = session.GetRunner();

var runOptions = new RunOptions
{
    TraceLevel = RunOptions.Types.TraceLevel.FullTrace
};

using (var stream = new MemoryStream())
{
    runOptions.WriteTo(stream);
    runner.RunOptions = new TFBuffer(stream.ToArray());
}

var runMetadata = new RunMetadata();
using (var stream = new MemoryStream())
{
    runMetadata.WriteTo(stream);
    runner.RunMetadata = new TFBuffer(stream.ToArray(), 0, 0);  // exception
}
```

Throws an exception, because the empty `RunMetadata` generates a zero-length buffer, which seems illegal to `TFBuffer.ctor`. However if I make the `RunMetadata` non-empty:

```
var runMetadata = new RunMetadata
{
    StepStats = new StepStats()
};
```

It then complains about passing in a non-empty RunMetadata.

If I set `RunOptions` without providing a `RunMetadata`, tensorflow crashes.
