### ISSUE TITLE
Is every feature included from Python bindings?

### ISSUE THREAD

**Issue by janissimsons** [migueldeicaza/TensorFlowSharp#296]
Does TensorFlowSharp include every feature that official Tensorflow python library has?
Are there any limitations to these bindings, when compared with other bindings (java, python etc)?

Thanks!

**Comment by migueldeicaza** [comment]
This is closer to the Go/Java APIs than the Python ones.

The Python API provides a large API surface on top of the core, which none of these languages currently expose fully.
