### ISSUE TITLE
Migrate all projects to new csproj/fsproj format

### ISSUE THREAD

**Issue by Andy-Wilkinson** [migueldeicaza/TensorFlowSharp#305]
Currently the TensorFlowSharp project is a mixture of the old .NET Framework style csproj/fsproj files using packages.config, and the modern .NET Core csproj files. I would propose standardising on the modern format.

Advantages would include,

- Ability to target 'netstandard'
- Simplified project file structure
- Less merges & merge conflicts when adding/removing files from the project
- Inclusion of the NuGet references in the same file (no need for packages.config)
- Ability to compile using the dotnet CLI (this works for both .NET Core and .NET framework projects)

**Comment by hanabi1224** [comment]
I have already created a PR to achieve this  https://github.com/migueldeicaza/TensorFlowSharp/pull/308

**Comment by Andy-Wilkinson** [comment]
That's great @hanabi1224 . Thanks.

**Comment by migueldeicaza** [comment]
It already supports .NET standard.

Most importantly, I develop on Visual Studio Mac with Mono, so I do not mind making changes, but whatever the outcome is, it should continue to work on VSMac + Mono.   This means that things like multi-targeting currently are not going to work until VSMac gets all the support it needs there.

**Comment by migueldeicaza** [comment]
Closing for now, we can reopen in the future.
