### ISSUE TITLE
Coding style suggestion: Include tensorflow commit hash when porting from python

### ISSUE THREAD

**Issue by Andy-Wilkinson** [migueldeicaza/TensorFlowSharp#307]
A lot of the code in TensorFlowSharp is likely to be a port of the Python code from the 'tensorflow' project. This is going to be a moving target, and it is very difficult to identify whether the code in TensorFlowSharp is out-of-date with respect to changes in the original Python code.

How about having a rule that any methods ported from the 'tensorflow' Python code include a comment as the first line referencing the original Python source file and the Git commit hash? This would then allow anyone to simply check whether there have been updates to the Python code since it was ported.

**Comment by Andy-Wilkinson** [comment]
Not sure it is the cleanest solution, but I can see it becoming a problem in the future. Maybe something to revisit as the codebase grows?

**Comment by migueldeicaza** [comment]
Yes, it is worth doing that, in particular if I start doing the porting of the higher level Python capabilities.
