### ISSUE TITLE
Exported frozen Model not working

### ISSUE THREAD

**Issue by aliBUT** [migueldeicaza/TensorFlowSharp#321]
**Describe the bug**
i used google's [object detection](https://github.com/tensorflow/models/tree/master/research/object_detection) sample to train and export a model using tensorflow 1.71. I also converted its extension to bytes and updated the label maps accordingly. For some reason, it is not loading the frozen graph at this line . but if I use default models available on the internet they work perfectly fine I just have to export them using tensor flow 1.71
**To Reproduce**
Train and export model and use it will this code  
https://github.com/MatthewHallberg/TensorFlowUnity-ImageClassification/blob/master/Assets/Scripts/Classification.cs

frozen model with label map 
https://www.dropbox.com/s/1uakcg534fl9d0n/Model.zip?dl=0

**Expected behavior**
It is supposed to load the model and return the estimation what is in the image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 1.71

**Additional context**
Only thing I am aware that it is supposed to export from the same version as my code. The models on the available by google work perfectly fine.

**Comment by oferbentovim** [comment]
I changed your model suffix to .pb and run it with the object detection example as in my ![ issue](https://github.com/migueldeicaza/TensorFlowSharp/issues/325) it runs but i get a lot of text as output and 2 objects are recognized on the image in the issue.
