### ISSUE TITLE
Gradient for Conv layers

### ISSUE THREAD

**Issue by AlejandroAlonso** [migueldeicaza/TensorFlowSharp#323]
**Is your feature request related to a problem? Please describe.**
I would like to compute the gradient of the decoder layer of a convolutional variational autoencoder. 

**Describe the solution you'd like**
Extend the API to cover the C++  gradients of Conv2D (and Conv2DTranspose ) networks. I think this will be very beneficial to the whole community.

**Describe alternatives you've considered**
Do it in python.

**Additional context**

**Comment by migueldeicaza** [comment]
Yes, this is a known issue, it is part of a much larger effort tracked in issues like this:

https://github.com/migueldeicaza/TensorFlowSharp/issues/253
