### ISSUE TITLE
Loading a keras model 

### ISSUE THREAD

**Issue by akuchotrani** [migueldeicaza/TensorFlowSharp#326]
I created a model using **Keras** in python and now I am trying to load the model model in tensorflow sharp using graph.Import method but I am getting **TensorFlow.TFException: 'Invalid GraphDef'** exception.

Is this exception because it couldn't load keras model which uses h5 extension. Do I need to convert it to tensorflow graph format pb?

I am stuck. Can anyone help me regarding this issue. Thanks.

**Comment by cpletz** [comment]
You might want to look at [this ](https://stackoverflow.com/questions/45466020/how-to-export-keras-h5-to-tensorflow-pb) stackoverflow question. The second answer solved the problem for me.

**Comment by akuchotrani** [comment]
@cpletz  Thanks for the help. I converted the keras model to tensorflow model and it worked perfectly.
I used executed this script that I found online : https://github.com/amir-abdi/keras_to_tensorflow

**Comment by sdg002** [comment]
Thank you.
