### ISSUE TITLE
TensorFlowSharp runs 5 times slower than in Python.

### ISSUE THREAD

**Issue by off99555** [migueldeicaza/TensorFlowSharp#330]
I have my `tensorflow.keras` model trained on python 3.6 then I converted it to `protobuf` graph to be used in Unity3D (game engine with TensorFlowSharp .dll plugin). My tensorflow version is 1.9.

Inside Unity TensorFlowSharp code, I measure `runner.Run()` execution time using `Stopwatch` and the elapsed time is around **25 ms** while in python `model.predict(X)` took only **5 ms**.
That's a huge difference and they are both on CPU. (I set `CUDA_VISIBLE_DEVICES=-1` before importing `tensorflow.keras` so it means that GPU was not utilized in python)

So how do I optimize the speed of `TensorFlowSharp` or is there a different way to make prediction time faster? Suggest me anything, I have a model and I want to predict it fast in Unity. I tried serving keras model via REST API and call via HTTP request but the I/O part is slow too.
And also, is `TensorFlowSharp` supposed to be slower than on `Python` even though they both run on CPU?

**Comment by malibu** [comment]
I have the same observation using many models from coco model repo below using TensorFlowSharp.

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

For example ssd_mobilenet_v1_coco_11_06_2017 took close to 7 secs for just  the following line: 
output = runner.Run();

Most of these models when tested in python observed inference time close to what is reported by google (CPU only) on the same machine -Xenon 8 core 2.4Hz 

Just to be clear, I'm not reporting the downloading time etc. in the example which was removed for my testing.

Any clues?

Thanks in Advance.

**Comment by boydy12** [comment]
I'm having a similar issue as malibu, it takes 4 seconds to run using the mobilenet model.
It printing a bunch out into the console over and over. It prints

```
Optimizing fused batch norm node name: "FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/FusedBatchNorm"
op: "FusedBatchNorm"
input: "FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/Conv2D"
input: "FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/gamma"
input: "FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/beta"
input: "FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/moving_mean"
input: "FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/BatchNorm/moving_variance"
device: "/job:localhost/replica:0/task:0/device:CPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 0.001
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

```
hundreds of times.

**Comment by malibu** [comment]
My issue is resolved! 

It really was the overhead from a new TFSession. Basically the first call to runner.Run() takes a lot of initialization time. If you're predicting multiple frames the subsequent "runs" take significantly lesser time, comparable to python prediction times.
So if you're predicting multiple frames do not re-create the session (BTW, I remember this to be an issue from initial python object detection sample as well). I have to say the example is also correct as it shows looping through the files within the using statement for the TFSession. Initially, I was only sampling one frame when I reported the issue. I can live with the initial overhead of 7 sec for session initialization as subsequent predictions work just fine.

Thanks!

**Comment by boydy12** [comment]
@malibu what sort of run times did you on subsequent frames?

**Comment by alex-zu** [comment]
>Inside Unity TensorFlowSharp code, I measure runner.Run() execution time using Stopwatch and the elapsed time is around 25 ms while in python model.predict(X) took only 5 ms.

--

>It really was the overhead from a new TFSession. Basically the first call to runner.Run() takes a lot of initialization time.

Observed a similar behavior for frozen models (models/variables size ~300-700 mb), but with models saved in SavedModel format there are no such problems.

**Comment by boydy12** [comment]
Fixed the issue, I was restarting the session each time. I needed to instantiate my object as a static object. It runs in 1/10 of the time now. Thanks @malibu!

**Comment by McCaulay** [comment]
I am having a similar issue;

The initialization time for the first run is Update() Time Taken: 17258.9034ms (17sec) which is fine, however the problem for me is that subsequent runs each take about 4.5 seconds to run.

```
Update() Time Taken: 4609.2594ms
Rectangle: 0.5601477, 0.481757, 0.6167338, 0.5052766
Rectangle: 0.5245463, 0.5383981, 0.5665582, 0.5582227
Update() Time Taken: 4576.6725ms
Rectangle: 0.401098, 0.8683129, 0.5747126, 0.9948973
Rectangle: 0.4080781, 0.1570649, 0.5833279, 0.2846136
Update() Time Taken: 4557.622ms
Rectangle: 0.5498077, 0.3543174, 0.5994084, 0.3898749
Rectangle: 0.1781026, 0.3149426, 0.2415893, 0.3597042
Update() Time Taken: 4582.6916ms
Rectangle: 0.4474752, 0.4020867, 0.6137465, 0.4917607
Rectangle: 0.4666583, 0.5205876, 0.5764902, 0.5736498
Update() Time Taken: 4742.1101ms
Rectangle: 0.4391254, 0.4033303, 0.6074172, 0.507664
Rectangle: 0.4642949, 0.5208328, 0.5714458, 0.5696045
Update() Time Taken: 4792.2455ms
```

Which is a problem as I am trying to run this against a live video feed. I'm using a custom object detection model and my frozen_inference_graph.pb is 185MB. The input images i used to train it on were 1920 x 1080 pixels. I am only initializing the TFSession once, and my video feed is 1920x1080.

My PC specs are;
Processor: Intel Core i7-6700K CPU @ 4.00GHz
Ram: 16GB
GPU: 4GB Nvidia GeForce GTX 970
Storage: 500GB SSD

Anyone any idea why it's running so slow? Only just started playing with Tensorflow today, my only thought is potentially the 1920x1080 image is too large.

**Comment by off99555** [comment]
It fixed my issue too!
I just run the statement `_tfSession = new TFSession(_graph);
` only when it is null instead of instantiating it every iteration and the prediction time reduced from 26 ms to 3 ms. Just one line of change can make a lot of improvement in the code!
This was very tricky bug as I thought measuring `runner.Run()` is enough without taking into account that `Run()` is not a pure function. It depends on the state of `runner` which depends on the state of `_tfSession`!

**Comment by funkysandman** [comment]
preserving the session across detections sped up things for me too - thanks

**Comment by mg021** [comment]
@malibu 
Can u send Your Code ??
I cant Understand .

**Comment by off99555** [comment]
> @malibu
> Can u send Your Code ??
> I cant Understand .
> i have this Problem

It will be better if you provide your code and we will be able to tell which line is the problem. Because the problem is very simple. You need to make sure that you don't call `new TFSession(...)` often. That's it!

**Comment by malibu** [comment]
Basically, the idea is to new up TFSession only once. As others have noted, there are many ways to achieve this, using static variables, if null check etc. within a code block. I created a class that encapsulates the tensor flow session once in the constructor and disposes it at the end.

The code below shows the core aspects of the class, some helper functions are omitted to make it concise.
This is what I have that worked (VS 2017, 2019, .net 4.6.1).  Code has reference to EMGU.CV types.

Hope this helps!
`///  Helper class, encapsulates TFSession for tensorflow object 
	
public class TensorFlowDetector :IDisposable
{

        // holds session, session and graph are reused when Detect() gets called
		private readonly TFSession _tfSession;
        private readonly TFGraph _modelGraph;
		
		///Constructor, pass in the frozen model path
        public TensorFlowDetector(string modelPath)
        {
            var modelBytes = File.ReadAllBytes(modelPath);
            _modelGraph = new TFGraph();
            _modelGraph.Import(new TFBuffer(modelBytes));
            _tfSession = new TFSession(_modelGraph);

        }
	     /// Accepts an EMGU Mat as image and returns boxes, scores and classes
	    public (float[,,] boxes, float[,] scores, float[,] classes) Detect(Mat imageData)
        {
           
	     /// Convert MAT -> JPEG -> Tensor in this call
            var tensor = ImageUtil.CreateTensorFromImage(imageData, TFDataType.UInt8);
            var runner = _tfSession.GetRunner();
            var timer = Stopwatch.StartNew();
            runner
                .AddInput(_modelGraph["image_tensor"][0], tensor)
                .Fetch(
                    _modelGraph["detection_boxes"][0],
                    _modelGraph["detection_scores"][0],
                    _modelGraph["detection_classes"][0],
                    _modelGraph["num_detections"][0]);

            var output = runner.Run();
            timer.Stop();

            Debug.WriteLine($"Detected boxes in {timer.ElapsedMilliseconds} ms");

            var boxes = (float[,,])output[0].GetValue(jagged: false);
            var scores = (float[,])output[1].GetValue(jagged: false);
            var classes = (float[,])output[2].GetValue(jagged: false);

            tensor.Dispose();

            return (boxes, scores, classes);
        }
		
	    ///Make sure private fields are disposed
	    protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    _modelGraph?.Dispose();
                    _tfSession?.Dispose();
                 }
                disposedValue = true;
            }
        }
} // End class
	
	///...........
	// Sample call pattern from clients of TensorFlowDetector class. 
	// First call takes longer (> 4 secs) and then falls off sharply for subsequent calls
	public void StartDetecting(string videoPath, string modelPath)
	{
		Mat mat;
		var  cap = new VideoCapture(videoPath);
		// detector is disposed at the end of using block
		using (var detector = new TensorFlowDetector(modelPath))
		{
			while ((mat = cap?.QueryFrame()) != null)
			{
				  var detections = detector?.Detect(mat);
				  //
				  .....
				 // do something with detections
			}
		}

	}`

**Comment by mg021** [comment]
@malibu @off99555 

helllo again 
this is my code 
in runner.Run() line 
it took close 16 sec
Can you help me ???

https://gist.github.com/mg021/ecb4444986006ec2826f2d92fa942ebc

thanks
