### ISSUE TITLE
Òbject Detection Example takes >40 seconds for inference

### ISSUE THREAD

**Issue by niallomahony93** [migueldeicaza/TensorFlowSharp#345]
![image](https://user-images.githubusercontent.com/9517193/46941888-0a205c00-d064-11e8-9ae4-0582af47e87d.png)
See attached image of RAM and CPU usage when running the example. The output result is correct once I aaply changes described in issue #325.

CPU is Intel i7, Windows 10 Enterprise (on a dual boot machine where Ubuntu 16.04 is also installed.

I am using the standard libtensorflow DLL that came with the project (TensorflowSharp 1.11.0).

Any ideas why it is taking so long?

**Comment by malibu** [comment]
I would make sure that you're timing just the call to "Run" without the overhead that some samples have in downloading, loading the graph etc. Also, make sure you run the inference multiple times without recreating the session as the first inference always takes longer.

Take a look at #330.

**Comment by niallomahony93** [comment]
Thanks malibu, 

When I run multiple times, without the loading the overhead each time, I get a much better inference time.

**Comment by JasonBSteele** [comment]
@niallomahony93 can I ask what sort of times you are getting for subsequent calls?

I am getting better performance but still not good: 54 seconds for the first run, 22 seconds for subsequent runs.

I am running it on an older laptop:
Intel Core i7 -3632QM CPU @ 2.20GHz
64 bit Windows 10 Pro v.1809
RAM 8 GB
SSD

...but even so!

**Comment by niallomahony93** [comment]
Sorry for my late reply, I am getting 9-10 fps inference for subsequent calls (that's including some delays in image acquisition)

**Comment by mg021** [comment]
@niallomahony93  
Hello ihave speed problem in 
runner.Run()   function . 
my speed Time is 16Second . 
do u know how resolve it ??
