### ISSUE TITLE
bazel no package error

### ISSUE THREAD

**Issue by okarpov** [migueldeicaza/TensorFlowSharp#35]
Hello, 

I want to build tensorflow dll but this command does not work for me:
bazel-0.4.4-windows-x86_64.exe build -c opt //tensorflow:libtensorflow.so

it gives the error:
ERROR: no such package 'tensorflow': BUILD file not found on package path.

What is that and how to fix it?

Thank you

**Comment by okarpov** [comment]
I have figured out first problem (or I think so at least)

and now I have the following output:

WARNING: C:/Users/OK/AppData/Local/Temp/_bazel_OK/gneAMNvi/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: 'BAZEL_PYTHON' is not set, start looking for python in PATH.
.
WARNING: C:/Users/OK/AppData/Local/Temp/_bazel_OK/gneAMNvi/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: Python found at .../Python/Python35/python.exe
.
WARNING: C:/Users/OK/AppData/Local/Temp/_bazel_OK/gneAMNvi/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: 'BAZEL_VS' is not set, start looking for the latest Visual Studio installed.
.
WARNING: C:/Users/OK/AppData/Local/Temp/_bazel_OK/gneAMNvi/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: Visual Studio found at C:\Program Files (x86)\Microsoft Visual Studio 14.0
.
INFO: Found 1 target...
INFO: Elapsed time: 1.548s, Critical Path: 0.02s


but where is the DLL that it builds? I can not find anything, it creates some short-cuts to folders but there are empty BIN folders.

Thank you

**Comment by migueldeicaza** [comment]
TensorFlow currently does not build on Windows out of the box, some work is being done in that area, but it is beyond the scope of my bindings here.

It is best to check on the tensorflow organization for that.
