### ISSUE TITLE
While running on Windows, are the folders under packages\TensorFlowSharp.1.11.0\runtimes neccessary?

### ISSUE THREAD

**Issue by sdg002** [migueldeicaza/TensorFlowSharp#352]
Hi All,
This is just a query. While checking in some simple source code that I had written using TensorFlowSharp Nuget packages into my source control, I realized that some of the files were huge. These belong to the **linux** and **osx** folders under **packages\TensorFlowSharp.1.11.0\runtimes** ?

Assuming that I am restricted to Windows , do you see any problems if I delete these folders?  My initial tests seem to indicate that this should be fine. Just checking with all of you.

Thanks,
Sau

**Comment by sdg002** [comment]
Just sharing an update with the community.
I have deleted the folders  **linux** and **osx** from **packages\TensorFlowSharp.1.11.0\runtimes** . This allowed me to overcome the Github errors during checkin because an individual file size was exceeding 100MB . No problems so far.   Not that I expected anything untoward. I believe I should be fine as long my end application is restricted to Windows operating system.

thanks.

**Comment by migueldeicaza** [comment]
You can remove them safely.

That said, I would not check into github any NuGet packages at all, those should be restored for you on first use.
