### ISSUE TITLE
Tensorflowsharp and Tensorflow 1.9 support for Unity

### ISSUE THREAD

**Issue by Vunooo** [migueldeicaza/TensorFlowSharp#363]
Hello,

I've been trying to use Tensorflowsharp for Unity (using Nuget package) in order to support TF 1.9, but then as I add ML-agents it tells me that multiple plugins exist with the name libtensorflow. What is the proper way to fix this?

I tried using the TensorflowSharp plugin from [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md) but it looks like this version only support TF 1.4.

Sorry if this is not the proper place to ask this as this is probably not an "issue" but I really don't know what to do.

Thank you so much.

**Comment by Sohojoe** [comment]
Is your problem getting ml-agents to work with any Tensorflow version? or do you need  v1.9?

ml-agents v0.5 only support Tensorflow 1.7.1 - I believe that you can train with later versions, but not for inference (running the trained model within unity)

This may all change with ml-agents v0.6 as Unity are releasing a new inference engine.

**Comment by Vunooo** [comment]
> Is your problem getting ml-agents to work with any Tensorflow version? or do you need v1.9?
> 
> ml-agents v0.5 only support Tensorflow 1.7.1 - I believe that you can train with later versions, but not for inference (running the trained model within unity)
> 
> This may all change with ml-agents v0.6 as Unity are releasing a new inference engine.


Thanks for the reply, buddy. And sorry for the late anwer. Finally I was able to make it run by importing Tensorflowsharp 1.11 from Nuge package through Unity, along with the ML-agents package it no longer gave me any problems.

Now the only issue that Im having is running it and making it work on Android. I just tested it on my phone and it's not classifying anything at all, so I guess it's some tensorflow issue.

Anyway, thank you so much!

**Comment by migueldeicaza** [comment]
I believe Unity has a custom fork of TensorFlowSharp that they distribute.
