### ISSUE TITLE
How to Detect Object in Xamarin Forms?

### ISSUE THREAD

**Issue by mosinms7711** [migueldeicaza/TensorFlowSharp#364]
I am working on one project where i need to click image and detect it using tensor flow api but i am confused how to use this API and is it Supported in Xamarin forms application.

**Comment by migueldeicaza** [comment]
My bad, start here:

https://www.customvision.ai/

Then download your native model for use with CoreML or TensorFlow.Lite on Android (https://www.nuget.org/packages/Xamarin.TensorFlow.Lite/)
