### ISSUE TITLE
How to convert Mat to TFTensor?

### ISSUE THREAD

**Issue by laolaolulu** [migueldeicaza/TensorFlowSharp#369]
![dd5046](https://user-images.githubusercontent.com/33310261/49196500-1a975680-f3c6-11e8-8391-cf8a472925af.png)

**Comment by migueldeicaza** [comment]
I have no clue what the "Mat" type is from the above.

**Comment by SimantoR** [comment]
Seems like the type **CV_8UC3** is not a supported datatype to feed into `impotmat`. Seems like an OpenCV problem, not a TF problem?
