### ISSUE TITLE
Xamarin mobile compatibility

### ISSUE THREAD

**Issue by marcusturewicz** [migueldeicaza/TensorFlowSharp#37]
Hi Miguel,

I know this project is still a work in progress and you have plans for this to be compatible with mobile. However, I was wondering when you would estimate this would be ready (at least for testing) in the mobile world on Xamarin.Android and Xamarin.iOS? And what would need to be progressed to get it to this stage?

**Comment by migueldeicaza** [comment]
It should just work, provided you get the dependencies for Android and iOS on your own.

At some point, someone should put together the entire NuGet package, similar to what we do for Urho or Skia, but doing that work is not fun, and I do this project purely for my own fun on weekends/nights.

Feel free to take a stab at it, look at how SkiaSharp does it: https://github.com/mono/SkiaSharp/
