### ISSUE TITLE
C# Strong Naming

### ISSUE THREAD

**Issue by AlejandroAlonso** [migueldeicaza/TensorFlowSharp#375]
**Is your feature request related to a problem? Please describe.**
We want to use TensorFlowSharp for our .net code and we need to strong name it. 

**Describe the solution you'd like**
We would like to know if there is a plan to strong name it, or if there are thoughts in that direction.

**Describe alternatives you've considered**
We will fork and strong name ourselves.

**Comment by migueldeicaza** [comment]
I do not have plans to strong name it at this point.

**Comment by tellarin** [comment]
@migueldeicaza we're also facing the same issue. Some projects release both strong-named and non-strong named version of their nuget packages, to keep both paths open. Would that be an option?
