### ISSUE TITLE
TensorFlowSharp Unity "'TensorflowSharp' does not exist in the current context" issue

### ISSUE THREAD

**Issue by Pennywise881** [migueldeicaza/TensorFlowSharp#379]
Hi there,

I am tying to build an object detection app using Unity with TensorFlowSharp. The app works when I run it in Unity but I can't get it to work on my android device. One thing to note is that in one of the scripts there are the following lines:

`#if UNITY_ANDROID
        TensorFlowSharp.Android.NativeBinding.Init();
#endif`

but I have to comment these out or else I get an error in both Unity and VS saying:
> error CS0103: The name `TensorFlowSharp' does not exist in the current context.

I tried to build the project by commenting these lines out, copied the APK onto my device and while it runs, it doesn't detect any objects. It just starts the camera and then that's it. I read that the above lines of code need to be there in order for this to work on android. 

I am completely new to using TensorFlow and TensorFlowSharp in Unity, therefore please let me know if I missed out anything. :)

**Comment by Pennywise881** [comment]
OK so I managed to fix this issue. I downloaded an older version of the plugin (v0.3) from here: [https://github.com/Syn-McJ/TFClassify-Unity](url)

After exporting it I got another error and the project wouldn't compile. This is the problem that I was facing: [https://github.com/Unity-Technologies/ml-agents/issues/979](url). Basically I couldn't run the project in the Editor anymore.

The fix was to check the "Editor" option on the TensorFlowSharp.Android import settings when building. In order to run it in the Editor I had to comment out
`#if UNITY_ANDROID TensorFlowSharp.Android.NativeBinding.Init(); #endif` line and uncheck the "Editor" option under "Include Platforms section" of the TensorFlowSharp.Android import settings.

**Comment by Cliwo** [comment]
@Pennywise881  
Hi, I'm facing same issue with you
I think There is no 'TensorFlowSharp.Android.NativeBinding.Init();' anymore and I'm trying to find solution for absent code...
Did you find another solution not using older version of the plugin?
If you found, pls let me know what you did.
If you did not find, Can you give me the plugin you used? 

Thank you

**Comment by ArghyaChatterjee** [comment]
Have anyone found the solution to this? I am facing the same issue.

**Comment by Arrjuun** [comment]
Facing the same problem.

Downloaded the version 0.3 mentioned above from the below link. Haven't tried it out myself. Hope this helps someone
https://s3.amazonaws.com/unity-ml-agents/0.3/TFSharpPlugin.unitypackage

**Comment by Guidosalimbeni** [comment]
Same issue, trying to build for webgl...? Or webgl is not supported?

**Comment by tywiggs** [comment]
#if UNITY_ANDROID
#if !UNITY_EDITOR
        TensorFlowSharp.Android.NativeBinding.Init();
#endif
#endif

this worked for me
