### ISSUE TITLE
TensorFlow.TFException:“Inconsistent values for attr 'T' DT_RESOURCE vs. DT_DOUBLE while building NodeDef 

### ISSUE THREAD

**Issue by CatAtHome** [migueldeicaza/TensorFlowSharp#384]
I am a complete beginner to Tensorflow.
An exception occurred while I was running the code:

var w = graph.Variable(graph.RandomUniform(new TFShape(y_size, x_size)));
var b = graph.Variable(graph.RandomUniform(new TFShape(y_size, depth)));
return act(graph.Add(graph.MatMul(w.VariableOp, x), b.VariableOp));

TensorFlow.TFException:“Inconsistent values for attr 'T' DT_RESOURCE vs. DT_DOUBLE while building NodeDef 'MatMul0' using Op<name=MatMul; signature=a:T, b:T -> product:T; attr=transpose_a:bool,default=false; attr=transpose_b:bool,default=false; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_COMPLEX128]>”

Anybody can solve my problem? Thanks

**Comment by flyinskybtx** [comment]
Did you solve the problem?
I come up to it today

**Comment by CatAtHome** [comment]
我英文很烂就不用英文了 这个问题并没有解决 那之后我用python的tensorflow库训练模型 然后用tensorflowsharp加载这个模型来绕过这个问题的。。。
