### ISSUE TITLE
Add support for placing an operation on a specific GPU.

### ISSUE THREAD

**Issue by zeahmed** [migueldeicaza/TensorFlowSharp#398]
The TensorFlow python version provides a way to place an operation on a specific GPU.

``` python
# Creates a graph.
with tf.device('/cpu:0'):
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))
```
This enables operations to be performed in parallel  using multiple GPUs. The TensorFlow C-API provides a method `TF_SetDevice` which can place an operation on a specific device.
https://github.com/tensorflow/tensorflow/blob/9f9efff916ed427b24216a739465842a09a8e136/tensorflow/c/c_api.h#L466

The only need is to call this method when creating an operation.

**Comment by festerx** [comment]
@zeahmed , did you get that to work? I have inference heavy app and 2 GPUs available, but I cannot load 2 models to run on 2 separate GPUs? Any ideas? Modifying protoConfig for 2 different sessions results in exception...

**Comment by zeahmed** [comment]
Yes, you can have a look this PR: https://github.com/migueldeicaza/TensorFlowSharp/pull/399 and the following test for more detail.
https://github.com/migueldeicaza/TensorFlowSharp/blob/cebc0741d8c8b39d2b7f563aec6b3531e28ca0e8/tests/TensorFlowSharp.Tests.CSharp/TensorTests.cs#L119

You can also look at the following test that trains the model in parallel using multiple GPUs.
https://github.com/migueldeicaza/TensorFlowSharp/blob/cebc0741d8c8b39d2b7f563aec6b3531e28ca0e8/tests/TensorFlowSharp.Tests.CSharp/OptimizerTests.cs#L481
