### ISSUE TITLE
incorrect win64 precompiled binary link

### ISSUE THREAD

**Issue by hawk977** [migueldeicaza/TensorFlowSharp#40]
Your precompiled uploaded binaries 

- libtensorflow-cpu-darwin-x86_64-1.0.0-rc0.tar.gz
- libtensorflow-gpu-darwin-x86_64-1.0.0-rc0.tar.gz
are the same as the linux ones.

There are .so files inside instead of .dll

**Comment by migueldeicaza** [comment]
There are no Win64 binaries yet.
