### ISSUE TITLE
GetValue() is too slow

### ISSUE THREAD

**Issue by sfdn123** [migueldeicaza/TensorFlowSharp#405]
Hi. im trying to Realtime-ML in Unity.
But im facing a problem that GetValue() method is too slow...
My output is an image with dimensions of (Height, Width, 3)
How can i resolve this problem??

**Comment by Keyang** [comment]
TFTensor in memory is flatten array. you can simply Marshal.Copy from tensor.Data to a managed array like byte[] or float[]

**Comment by sfdn123** [comment]
Thanks so much!!
