### ISSUE TITLE
TFTensor.GetValue appears to be transposing multidimensional arrays.

### ISSUE THREAD

**Issue by andykernahan** [migueldeicaza/TensorFlowSharp#42]
Hello,

`TFTensor.GetValue` appears to be transposing multidimensional arrays.

Specifically, I believe that [`FetchMultiDimensionalArray`](/migueldeicaza/TensorFlowSharp/blob/master/TensorFlowSharp/Tensor.cs#L821) is updating the `target` array in column major order, whereas `data` is [documented](/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h#L183) to be in row major order.

**Version Used:**

Library | Version
------------ | -------------
libtensorflow.dll | r1 (local Windows cmake build)
TensorFlowSharp.dll | 39eb920ee213e0f6a67925e9429b3c7723963173

**Reproduction:**

The following program effectively roundtrips a 2-D array:

```csharp
public static void Main(string[] args)
{
    var graph = new TFGraph();
    var input = graph.Placeholder(TFDataType.Int32);
    var output = graph.Identity(input);
    using (var session = new TFSession(graph))
    {
        var expected = new int[,] {{0, 1}, {2, 3}};

        var runner = session.GetRunner();
        runner.AddInput(input, expected).Fetch(output);

        var actual = (int[,])runner.Run()[0].GetValue();

        Console.WriteLine($"Expected: {RowOrderJoin(expected)}"); // 0, 1, 2, 3
        Console.WriteLine($"Actual:   {RowOrderJoin(actual)}");   // 0, 2, 1, 3
    }
}
private static string RowOrderJoin(Array array) => String.Join(", ", array.Cast<int>());
```

**Expected Behaviour:**

The `expected` and `actual` arrays are equivalent.

**Actual Behaviour:**

The `actual` array appears to be transposed.

Cheers.

**Comment by andykernahan** [comment]
Upon further investigation, `GetValue(jagged: true)` (specifically [`FetchJaggedArray`](/migueldeicaza/TensorFlowSharp/blob/d74e95d3016e0fce3b5edc265963c420e4e63f71/TensorFlowSharp/Tensor.cs#L740)) updates the `target` array in row major order, which I believe to be correct.

I'm happy to submit a PR, assuming it's agreed that the multidimensional behaviour is incorrect.

**Comment by migueldeicaza** [comment]
Good catch, please submit a pull request.

**Comment by andykernahan** [comment]
Done: #46

**Comment by migueldeicaza** [comment]
Merged, thanks!
