### ISSUE TITLE
Op type not registered 'LeakyRelu' in binary running 

### ISSUE THREAD

**Issue by jetjodh** [migueldeicaza/TensorFlowSharp#443]
I am trying to build an inference binary in c# but am getting an OP type not registered error. Is this not present in tf 1.13.1 or some other problem? I froze this graph in tf 1.13.1 from keras model.

**Error Log:**
Exception thrown: 'TensorFlow.TFException' in TensorFlowSharp.dll
An unhandled exception of type 'TensorFlow.TFException' occurred in TensorFlowSharp.dll
Op type not registered 'LeakyRelu' in binary running on JET. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by hamwich3** [comment]
Did you ever figure anything out on this? I'm having the same issue

**Comment by jetjodh** [comment]
That's a great tip! But I went another way and ended up implementing the whole project in native using PyTorch.
