### ISSUE TITLE
tensorflow ocaml-like f# api 

### ISSUE THREAD

**Issue by Neftedollar** [migueldeicaza/TensorFlowSharp#45]
Hi! I think OCaml example API will be helpfull
https://github.com/LaurentMazare/tensorflow-ocaml

**Comment by migueldeicaza** [comment]
Please be specific.  If you mean the high-level framework that is built on top of it, I believe that should likely be done as a separate project on top of the core bindings.

**Comment by Neftedollar** [comment]
Ok, thank you.
