### ISSUE TITLE
TensorflowSharp with Tensorflow-GPU

### ISSUE THREAD

**Issue by Kjos** [migueldeicaza/TensorFlowSharp#452]
**Describe the bug**
I have TensorflowSharp running successfully on CPU; my model gives expected output.
I have Tensorflow 1.14 running successfully locally on GPU using CUDA 10.0 and CUDNN 7.6 (with python).
I would like to run TensorflowSharp on GPU, so replaced the libtensorflow.dll with _pywrap_tensorflow_internal.pyd (renamed to libtensorflow.dll) in 'packages\TensorFlowSharp.1.13.0\runtimes\win7-x64'. I also set the compile architecture to x64. 
It loads the dll successfully, however it will always throw a CUDNN mismatch error.

**To Reproduce**
See above.

Note: I do not have time to create models, train models, create samples from scratch and then adding your 3-4 lines of code to a sample to debug your problem.   You need to provide a complete test case.

**Expected behavior**
I would figure it would run on GPU fine, since it runs fine from python as well.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**

**Additional context**

I filed this as a bug, however I can see how it is perhaps more so a feature as GPU support is not yet implemented.

Am I missing a DLL reference? The other threads about GPU support don't seem to have encountered this issue.

**Comment by Kjos** [comment]
Got it to work with 10! It's a bug within CUDA, not TF#.
You need to set the ProtoConfig to Allow Growth.


```
            TFSessionOptions options = new TFSessionOptions();
            unsafe
            {
                byte[] GPUConfig = new byte[] { 0x32, 0x0b, 0x09, 0x33, 0x33, 0x33, 0x33, 0x33, 0x33, 0xd3, 0x3f, 0x20, 0x01 };
                fixed (void* ptr = &GPUConfig[0])
                {
                    options.SetConfig(new IntPtr(ptr), GPUConfig.Length);
                }
            }
            this.session = new TFSession(this.graph, options);
```

The speedup is amazing!

**Comment by bbhxwl** [comment]
> Got it to work with 10! It's a bug within CUDA, not TF#.
> You need to set the ProtoConfig to Allow Growth.
> 
> ```
>             TFSessionOptions options = new TFSessionOptions();
>             unsafe
>             {
>                
>                 byte[] GPUConfig = new byte[] { 0x32, 0x02, 0x20, 0x01 };
>                 fixed (void* ptr = &GPUConfig[0])
>                 {
>                     options.SetConfig(new IntPtr(ptr), GPUConfig.Length);
>                 }
>             }
>             this.session = new TFSession(this.graph, options);
> ```
> 
> The speedup is amazing!

What do I need to install to run GPU?

**Comment by Kjos** [comment]
Phenix library or sometihgn

Op do 1 apr. 2021 om 06:26 schreef bbhxwl ***@***.***>:
