### ISSUE TITLE
libtensorflow for arm64 architecture

### ISSUE THREAD

**Issue by SestoAle** [migueldeicaza/TensorFlowSharp#463]
Hi!

I used TensorFlowSharp with Unity to make a project for mobile systems. Due to the new Android requirements, I need to deploy an arm64 version of my game, but I'm no able to build tensorflow and create a libtensorflow.so for this kind of systems.

I found various solutions on the internet but none seem to work (or they are too complex to follow), is there anyone who can help me find a simple solution to build tensorflow for arm64 or anyone who has a libtensorflow.so already compiled for arm64?

I'm using macOS Catalina to work.

Thanks!

**Comment by gmlwns2000** [comment]
I have only pretty out dated binary... I built it my project for while ago. [link](https://drive.google.com/open?id=1RNHTLujFPzrdjUHL77g75xrVb5auAW2J)

By the way, you could build yourself too.

1. Clone tensorflow
2. Edit [version_script.Ids](https://github.com/tensorflow/tensorflow/blob/54a01684b1cedaa93272aba4169da845155aae9b/tensorflow/contrib/android/jni/version_script.lds#L7). Add `TF_*` at line 7.
3. Follow [this page](https://github.com/tensorflow/tensorflow/tree/54a01684b1cedaa93272aba4169da845155aae9b/tensorflow/contrib/android#bazel), and copy artifact (`bazel-bin/tensorflow/contrib/android/libtensorflow_inference.so`)

**Comment by SestoAle** [comment]
Thanks! I was able to compile the library for arm64 by myself, thanks for the tips!
