### ISSUE TITLE
Possibly unnecessary or buggy branching when fetching jagged arrays?

### ISSUE THREAD

**Issue by ddurschlag** [migueldeicaza/TensorFlowSharp#48]
Specifically here: https://github.com/migueldeicaza/TensorFlowSharp/blob/1e267e83ad1e19e6a2f333f5363de8186c2da782/TensorFlowSharp/Tensor.cs#L795-L814

As far as I can tell, the only difference between these two branches is the casting of top (a long) to int and its subsequent assignment to itop. However, these variables are only used in a for loop with an int counter.

This leaves me with two questions:

1) Is this branching necessary? Seems like we could just always use int for both "top" and the loop counter. I don't think there's support for arrays with more than Int32.MaxValue dimension in .Net. That said, throwing a "too long array" exception might also be acceptable, since this simply ignoring a chunk of the data also seems bad. I don't know tensorflow well enough to comment on the appropriate API behavior here.

2) Is this code currently buggy? If top is, in fact, greater than the max value of an int32, won't "l" (the integer counter for the for loop in that branch) wrap and never reach it?

**Comment by migueldeicaza** [comment]
You are correct, it should be a long.

Yes, the element count in an array can be larger than Int32.Maxvalue.

**Comment by ddurschlag** [comment]
I might be a missing something, but my understanding was that, while an array can have more than Int32.MaxValue items, the length of any individual dimension is thus limited. Specifically, looking at Mono's implementation (https://github.com/mono/mono/blob/master/mcs/class/corlib/System/Array.cs), there are 13 extern'd delegations to the underlying implementation:

		internal extern void GetGenericValueImpl<T> (int pos, out T value);
		internal extern void SetGenericValueImpl<T> (int pos, ref T value);
		extern int GetRank ();
		public extern int GetLength (int dimension);
		public extern int GetLowerBound (int dimension);
		public extern object GetValue (params int[] indices);
		public extern void SetValue (object value, params int[] indices);
		internal extern object GetValueImpl (int pos);
		internal extern void SetValueImpl (object value, int pos);
		internal extern static bool FastCopy (Array source, int source_idx, Array dest, int dest_idx, int length);
		internal extern static Array CreateInstanceImpl (Type elementType, int[] lengths, int[] bounds);
		static extern void ClearInternal (Array a, int index, int count);
		public extern object Clone ();

...none of which use long. Given this, it seems like the sum of all elements of Shape can be greater than Int32.MaxValue, but any individual element cannot be. Am I misunderstanding something somewhere?

**Comment by migueldeicaza** [comment]
Just a limitation of the Mono runtime, not the .NET runtime.

**Comment by migueldeicaza** [comment]
fixed that one
