### ISSUE TITLE
Compile error on Ubuntu and Monodevelop. 

### ISSUE THREAD

**Issue by evindj** [migueldeicaza/TensorFlowSharp#50]
System.Buffer does not contain definition for MemoryCopy in Tensor.cs line 678. My framework target is Mono/.NET4.5, it looks like this method is new to the .net framework, should I target Mono/ .NET 4.5 on Ubuntu for this project?

**Comment by evindj** [comment]
It's all find, I installed dotnet core and shifted to .Net Framework and it compiled correctly.

**Comment by cirovarriale** [comment]
Sorry if I rewrite on this old issue, but I'm trying to run TensorFlowSharp on Ubuntu 18.04 without results. I installed the last version of dotnet:

`dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.105 [/usr/share/dotnet/sdk]
  2.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
`
obviously when I try to give:
`dotnet build TensorFlowSharp.sln`
the system tells me that can't find the .NET Framework 4.6.1 targeted in some .csproj file. 
On linux system we have .NET Core, or at least .NET Standard, but not Framework.

How can I solve this issue?

Best regards.
Ciro
