### ISSUE TITLE
Exception executing sample test on Ubuntu

### ISSUE THREAD

**Issue by evindj** [migueldeicaza/TensorFlowSharp#51]
Tensorflow.cs throws a SystemEntryPointNotFound at line 731. any idea what could be going on?

**Comment by andykernahan** [comment]
`TF_NewWhile` was defined in release v1.1.0; ensure you are using at least that version of libtensorflow.

**Comment by migueldeicaza** [comment]
You can do that, or avoid using the "While" construct (you are probably running into it due to the samples just having a collection of API exercising features).

**Comment by evindj** [comment]
Thanks upgrading to r1.1 worked. I will be able to contribute model when support for gradient is added.
