### ISSUE TITLE
Use of Models

### ISSUE THREAD

**Issue by vsjc91** [migueldeicaza/TensorFlowSharp#52]
Can you please provide guidance on how I could access syntaxnet dragnn from C# either directly from (or by extending) TensorFlowSharp?

https://github.com/tensorflow/models/tree/master/syntaxnet/examples/dragnn

Thanks

**Comment by migueldeicaza** [comment]
This will not be easy.

SyntaxNet is an extension to TensorFlow that you must compile independently and load into TensorFlow.

If you wanted to use it, you would need to do that compilation, and the "bind" that engine and surface it into C#.
