### ISSUE TITLE
Import InceptionV3 throws "Invalid GraphDef" error

### ISSUE THREAD

**Issue by AdamStefan** [migueldeicaza/TensorFlowSharp#54]
Hi,
I've tried to import the [InceptionV3](http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz) using the following code:
   var model = File.ReadAllBytes(modelFile);
   var graph = new TFGraph();
   graph.Import(model, "");

-- Unhandled exception of type TFException  "Invalid GraphDef"

It looks like for all graphs bigger than approx 70 Mb this exception is thrown.

Thx

**Comment by migueldeicaza** [comment]
Yeah, that seems to be a common problem with Tensorflow and Protobuf.   I believe someone suggested a way somewhere to recompile the underlying protocol buffer implementation in libtensorflow with a larger buffer size.   I do not recall where I saw that.

This is what stops one of our samples as well, the file is too large.

**Comment by migueldeicaza** [comment]
This is the tensorflow issue, it should be addressed if you upgrade your TensorFlow runtime:

https://github.com/tensorflow/tensorflow/issues/582

**Comment by khanyuriy** [comment]
I have the same error, but my model less then 64MB.
How can i be sure, that TensorFlowSharp bindings are compatible with savedmodel file i have got?

**Comment by csharpner** [comment]
My model is only 84KB and I have another that's 69KB and I get this error on both of them.  Latest version of TensorFlowSharp available in NuGet as of 2019-02-01 and TensorFlow 1.12.0.  I've not been able to get TensorFlowSharp to work at all.  Is there an alternative way to use a TensorFlow .pb model file from a C# app?

**Comment by codingyoutub** [comment]
I have the same problem. I made a pb file with a teachable machine, but it seems to be a compatibility problem. I think it's 2.3 version of pb. Did you find a solution?

**Comment by migueldeicaza** [comment]
I recommend you now use TensorFlow.NET which is being actively developed.

**Comment by Nevey** [comment]
> I recommend you now use TensorFlow.NET which is being actively developed.

I can't explain why, but it's a pain in the ass getting that library to work in Unity. Tensorflowsharp seems a lot easier to deal with, but I'm also running into the `TFException "Invalid GraphDef"` issue. You said this has to do with the version of TensorFlow used to create the model? Any tips for me? (I'm running a python project to train data, then I want to read it in Unity)
