### ISSUE TITLE
Session.run requires outputs

### ISSUE THREAD

**Issue by r3db** [migueldeicaza/TensorFlowSharp#70]
Hi, I'm not able to convert this simple python example into C#.

```python
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

c = 3 * (a + b)

print(session.run(c, { a: 1, b: 4}))
```

Here's my attempt:
```csharp
var a = graph.Placeholder(TFDataType.Float, operName: "a");
var b = graph.Placeholder(TFDataType.Float, operName: "b");

var c = graph.Mul(graph.Const(3f), graph.Add(a, b));
            
using (var session = new TFSession(graph))
{
    var result = session.Run(new[] {c}, new TFTensor[] {1f, 4f}, null);
}
```

When I run it, it forces me to specify the outputs, (which the python version does not)
I'm not really sure what to put there.

PS: I would love to see more examples on how to use this API.
For example MNIST Training and Inference for noobs like me.

Cheers.

**Comment by migueldeicaza** [comment]
Agreed.  

I started on some work to prepare the MNIST data set, you can find it on the "Learn" directory, but have not completed it.    The code in Learn is just a number of utilities that I have been porting to work with some datasets (currently limited to one dataset :-).

I should complete that work.

Agreed on the need for more samples like that, in fact, the major driver to write more samples is to find out what areas of the API work well and which ones could use improvements.    

I thought that porting the Keras high-level API as a big sample would be useful, but while it might get the job done, internally it is quite ugly and the untangling has been quite time consuming.   I have not made as much progress as I wish I had.

**Comment by migueldeicaza** [comment]
This particular case can be shown on the SampleTest:

https://github.com/migueldeicaza/TensorFlowSharp/blob/639655be5c3a81b474f06e2b90bf770f796f7b6a/SampleTest/SampleTest.cs#L329

**Comment by migueldeicaza** [comment]
Btw, I just realized you are using the low-level API.

There is a `session.GetRunner()` that is a lot simpler to use.   The samples illustrate how to use it, but code completion should help you there as well.

**Comment by r3db** [comment]
Just figured out the correct usage, thanks.
It differs a bit from tensorflow.

```csharp;            
using (var session = new TFSession(graph))
{
    var result = session.Run(new[] {a, b}, new TFTensor[] {1f, 4f}, new[] { c });
}
```

I'm just started **trying** to learn tensorflow, your API is a great way to start.
If I can somehow help, let me know.

**Comment by migueldeicaza** [comment]
You are using the full API binding, that is a raw surfacing of the C API, and while precise, it is cumbersome.   That is why I copied the design of the Java API with the call to `GetRunner` on the session, in particular it frees you from manually having to pair outputs and tensors.
