### ISSUE TITLE
Text summarization in C#

### ISSUE THREAD

**Issue by Snehasishmisra** [migueldeicaza/TensorFlowSharp#73]
Hi,
I am new to tensorflow. I have requirement to use text summarization from .Net code.I have taken the latest code but it has erros and it's not building.How to use this code for text sumarization and guide how can we integrate tensorflow with c# for summarization. Thanks.

**Comment by migueldeicaza** [comment]
Use the NuGet package.

As for text summarization, that is beyond the scope of the Github issues, it is only to report issues with the binding itself.
