### ISSUE TITLE
Image Decorder for TF ?

### ISSUE THREAD

**Issue by Toshiro-Hitsugaya** [migueldeicaza/TensorFlowSharp#78]
I am trying to make an application that will use inception by google to recognize objects. Can anyone help me understand which classes do what ? I was able to import tensorflowsharp to my project and I tried to directly pass the file as an array to a tensor but that gave me errors. I have never used TF. That's why I am not sure how to use any of these classes.

**Comment by Toshiro-Hitsugaya** [comment]
using System;
using TensorFlow;
using System.IO;


namespace TensorFlowTest
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var graph = new TFGraph())
            {
                graph.Import(File.ReadAllBytes(@"C:\Users\Shaamil\Desktop\inception-master\inception_tensors.pb"));
                var session = new TFSession(graph);
                var runner = session.GetRunner();

                runner.AddInput(graph["input"][0], );
                runner.Fetch(graph["output"][0]);

                var output = runner.Run();

                // Fetch the results from output:
                TFTensor result = output[0];
                Console.WriteLine(result);
                Console.ReadLine();
            }
        }
    }
}

This is the code I tested out if you need to know what exactly I did... thnx in advance

**Comment by migueldeicaza** [comment]
Can you provide a link to the model that you are trying to run?

**Comment by msnh2012** [comment]
I tried to export a model which the "placeholder" was like this:
`tf.placeholder(tf.uint8,[None,None,None],name='input')`.
And in C#, I fed the model with byte[]. But It didn't work. Maybe I should reshape it in C#, I'm working on it.

**Comment by Toshiro-Hitsugaya** [comment]
@migueldeicaza 
https://github.com/tensorflow/models/blob/master/slim/README.md#pre-trained-models

**Comment by Toshiro-Hitsugaya** [comment]
The example project "ExampleInceptionInference" was of big help. I think I know what I have enough information to continue with my project. Sincerely Thank you <3

**Comment by Toshiro-Hitsugaya** [comment]
![image](https://user-images.githubusercontent.com/13829948/27501809-2ac70f84-5889-11e7-81fa-1df02ebe2c6b.png)
I spoke too soon... What does that mean ?

**Comment by Toshiro-Hitsugaya** [comment]
![image](https://user-images.githubusercontent.com/13829948/27501864-8245f40a-5889-11e7-80f2-11c6df17900c.png)
Never mind Fixed thanks guys... you have no idea how much your help meant to me... I couldn't have done this without u... thanks alot

**Comment by Toshiro-Hitsugaya** [comment]
Next step is to learn how to retrain the model using other pictures and save the new model to a usable file :')

**Comment by doxakis** [comment]
Hi,
if you want to see some examples : https://github.com/doxakis/MachineLearningSharp/
This is various experiments (OCR, Tensorflow, etc.) on c#
I am using the inception v3 model.

I suggest you to take a look at : https://github.com/doxakis/MachineLearningSharp/blob/master/TensorFlowAsAService/TensorFlowClassificationWrapper.cs

Make sure you have enough RAM.
