### ISSUE TITLE
How to convert TFTensor to TFOutput

### ISSUE THREAD

**Issue by cesarsouza** [migueldeicaza/TensorFlowSharp#81]
Hi,

This is not actually an issue but rather a question. This might be a stupid question actually, but how do I convert a TFTensor or a TFInput to a TFOutput such that I can use in TFGraph.MatMul()?

To give a concrete example, let's say I have a method that accepts a TFInput, as well as a ```TFTensor``` field in my class called ```kernel```, what do I have to do so that I can use it in some way similar to:

```csharp
public TFOutput Call(TFInput inputs)
{
    TFOutput output = Graph.MatMul(inputs, this.kernel));
    return output;
}
```

and still have it compile? Right now I am getting errors "Cannot convert from TensorFlow.TFTensor to TensorFlow.TFOutput" with the code above, though I am pretty sure its because I have not understood completely how to mix those two together.

Regards,
Cesar

**Comment by migueldeicaza** [comment]
To turn a `TFTensor` into a `TFOutput`, you will want to use the `TFGraph`'s. `Const` method.   This will turn the tensor into a constant that you can then use.

For example here, I create a `TFOutput` from the `Tensor` 2 (there is an implicit conversion that convers that 1 into a `TFTensor`):

https://github.com/migueldeicaza/TensorFlowSharp/blob/2804490d9c58d59625929ad9da8db607f50c809c/SampleTest/SampleTest.cs#L55

Or here with a matrix:

https://github.com/migueldeicaza/TensorFlowSharp/blob/2804490d9c58d59625929ad9da8db607f50c809c/SampleTest/SampleTest.cs#L175
