### ISSUE TITLE
How to import .ckpt file ?

### ISSUE THREAD

**Issue by Toshiro-Hitsugaya** [migueldeicaza/TensorFlowSharp#85]
How do I import .ckpt file ? I understand how to import a .pb file but what about a .ckpt file ?

**Comment by Toshiro-Hitsugaya** [comment]
For example inception model v4 from https://github.com/tensorflow/models/blob/master/slim/README.md#pre-trained-models is a .ckpt file

**Comment by gmlwns2000** [comment]
[http://www.mattrajca.com/2016/11/25/getting-started-with-deep-mnist-and-tensorflow-on-ios.html](http://www.mattrajca.com/2016/11/25/getting-started-with-deep-mnist-and-tensorflow-on-ios.html)
It seems we need to package .pb, and .ckpt into one .pb file to import and run it.

**Comment by Toshiro-Hitsugaya** [comment]
how do I do that in tensorflowsharp ?

**Comment by LuJyKa** [comment]
### 1. Make a Frozen Model File(.pb) which both contains graph defs & weights.
First, Save original pb file & checkpoint file
Python Code
``` Python
# Save checkpoint file
tSaver = tf.train.Saver();
tSaver.save( tSess, "Profile.ckpt"); # It will generate 4 files: checkpoint, Profile.ckpt.index, Profile.ckpt.meta, Profile.ckpt.data-00000-of-00001

# Save pb file
tf.train.write_graph( Session.graph_def, "LogFolder", 'Profile.pb', as_text=True )
Command
```
Then, Use freeze_graph.py to merge them into a frozen model .pb file
(some argument need to adjust when using)
``` cmd
python "Python\Lib\site-packages\tensorflow\python\tools\freeze_graph.py" --input_graph=.\Profile.pb --input_checkpoint=.\Profile.ckpt --output_node_names=Output/Predictions,Output/Loss --output_graph=frozen.pb 
pause
```
### 2. Import this pb file in code:
C# Code
``` C#
using (var graph = new TFGraph())
{	

	graph.Import(File.ReadAllBytes("frozen.pb"),"");
	var session = new TFSession(graph);
	var runner = session.GetRunner();
	runner.AddInput(graph["Input/IsTraining"][0], false);

	runner.AddInput(graph["Input/Values"][0], new TensorFlow.TFTensor(TFDataType.Float, new long[]{1,44,60},1*44*60*4));
	runner.Fetch(graph["Output/Predictions"][0]);

	var output = runner.Run();

	// Fetch the results from output:
	TFTensor result = output[0];
}
```
