### ISSUE TITLE
I would like to use tensorflow in xamarin, is there a relevant example?

### ISSUE THREAD

**Issue by szdree** [migueldeicaza/TensorFlowSharp#88]
I would like to use tensorflow in xamarin, is there a relevant example?

**Comment by gmlwns2000** [comment]
Hi @szdree,
Tensorflow for mobile is already discussed in #43.
And this is inference test code in my xamarin project. [See code](https://github.com/gmlwns2000/Vision/blob/master/Vision/Tests/InceptionTests.cs)
I hope this can help you.

**Comment by migueldeicaza** [comment]
Already being tracked elsewhere

**Comment by pooran** [comment]
https://blog.xamarin.com/android-apps-tensorflow/
