### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by lefig** [migueldeicaza/TensorFlowSharp#89]
Hi, I am struggling with building this great project. I am running VS 2015 with all the updates. It looks like a build configuration issue as I am picking up 1000+ errors such as
1>C:\work\ML\Tensorflow\dotnet\TensorFlowSharp\TensorFlowSharp\Operations.g.cs(506,10,506,11): error CS1519: Invalid token '(' in class, struct, or interface member declaration
1>C:\work\ML\Tensorflow\dotnet\TensorFlowSharp\TensorFlowSharp\Tensorflow.cs(2133,61,2133,64): error CS1003: Syntax error, ',' expected
1>C:\work\ML\Tensorflow\dotnet\TensorFlowSharp\TensorFlowSharp\Operations.g.cs(506,40,506,48): error CS1044: Cannot use more than one type in a for, using, fixed, or declaration statement
1>C:\work\ML\Tensorflow\dotnet\TensorFlowSharp\TensorFlowSharp\Operations.g.cs(506,49,506,68): error CS1002: ; expected
1

I would appreciate any suggestions!

**Comment by andykernahan** [comment]
The project uses C#7 language features; the first build error relates to a method that returns a tuple using the new syntax. I do not believe that VS2015 supports C#7 out of the box.

**Comment by migueldeicaza** [comment]
@andykernahan is correct, this project needs C# 7

**Comment by lefig** [comment]
Thank you both. I appreciate your support. Yes, it looks like VS 2017 is the way to go.
