### ISSUE TITLE
how to fix error install Tensorflowsharp

### ISSUE THREAD

**Issue by thuanssss** [migueldeicaza/TensorFlowSharp#90]
When I install nutget tensorflowsharp.1.2.2, some errors occur. This is the error log:

"The attribute "CopyToOutputDirectory" in element <None> is unrecognized.  C:\Users\Thuan Nguyen\Desktop\ConsoleApplication1\packages\TensorFlowSharp.1.2.2\build\TensorFlowSharp.targets"

How can I fix that error? May you give me some advices.

**Comment by migueldeicaza** [comment]
Are you using Visual Studio 2017?

**Comment by taier** [comment]
Face the same error, when open from Xamarin Studio Mac. If I run the project from Visual Studio Mac, all works great.

**Comment by mdabros** [comment]
I get the same error when using Visual Studio 2015. With Visual Studio 2017 it works without any issues.

**Comment by Toshiro-Hitsugaya** [comment]
Here's how I fixed this error when I encountered it... I downloaded the nugget package... renamed it to ".rar" extracted the files... there'll be a folder called "native" ignore that folder for now and go back to VS and manually add the reference to the .dll file in the other folder... and then once u have added the reference select all the files within the native folder, drag and drop them onto the solution explorer AND while all those files are selected open the properties tab and change CopyToOutputDirectory property from Never to Always... Good luck

**Comment by falahati** [comment]
For now, after an unsuccessful installation, remove the package and go to:
`C:\Users\{YOURUSERNAME}\.nuget\packages\TensorFlowSharp\1.2.2\build`
Replace the `TensorFlowSharp.targets` file with the modified version posted in the above commit, and then, try installing it again using Visual Studio.

**Comment by markringo** [comment]
@falahati I'm using Visual Studio 2013 Ultimate and there's no ".nuget" folder in the directory you mentioned. But in `C:\Users\{MYNAME}\AppData\Local\NuGet\Cache` I got the package files. I renamed the package and replaced the ".target" file with the committed version, tried installing it via console, but no luck. Did I miss anything?

**Comment by falahati** [comment]
What is the exact error message after doing so? Is it the same as OP message?
And what is your nuget version?

**Comment by markringo** [comment]
No bother, Just now I cleaned everything in the cache and re-download the package from Nuget manager and it is installed without any problem.

**Comment by brianberns** [comment]
Why is this issue closed? TensorFlowSharp cannot be installed successfully from NuGet using VS2015. I'm having the exact same issue.
