### ISSUE TITLE
 create a tensor of string list

### ISSUE THREAD

**Issue by tcmxx** [migueldeicaza/TensorFlowSharp#95]
Hello, 
I am trying to create a tensor of a list of string. Currently I only found the CreateString(), which only creates a scalar tensor of string I think. Am I wrong or is there a way to create a tensor of multiple strings?

**Comment by migueldeicaza** [comment]
There is currently no simple way of doing that with the binding.

What you need to do is create a new tensor with `new TFTensor (TFDataType dataType, long [] dims, int size)` and then you would need to manually invoke some of the APIs to fill the data with your information (`TF_StringEncode`) and so on.

Ideally we would have a CreateString that takes an `Array` for scenarios where you can load the data from a multi-dimensional array, and perhaps a convenience `IEnumerable<byte []>` for vectors of strings.

**Comment by tcmxx** [comment]
@migueldeicaza Thanks for reply!
However, I did not find out how to fill the data manually. Could you tell me which API to use? I am using the NuGet packet btw.

**Comment by migueldeicaza** [comment]
I did on my previous comment, you will need to look at the source code for `CreateString`.

**Comment by tcmxx** [comment]
Thanks!  i will check the sourcecode.

**Comment by azmathmoosa** [comment]
@tcmxx hey, did you manage to do this?  I would be grateful if you could share your code.  Thanks.

**Comment by tcmxx** [comment]
@azmathmoosa Sorry that I did not use string in the end.

**Comment by azmathmoosa** [comment]
@tcmxx thanks for replying! its okay.  I don't think I can use this library.
